[package]
name = "bridge-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bridge-domain.workspace = true
base64 = "0.22"
regex = "1"
serde_json.workspace = true
toml = { workspace = true }
url.workspace = true
nix.workspace = true
toml_edit = "0.22"

