(async()=>{
 const invoke=window.__TAURI_INTERNALS__.invoke;
 const checks={};
 try {
  for(let i=0;i<100&&!document.querySelector('.brand');i++)await new Promise(r=>setTimeout(r,50));
  if(!document.querySelector('.brand'))throw Error('frontend_missing');checks.react_rendered=true;
  const projects=await invoke('projects');if(projects.length!==1||projects[0].id!=='proof')throw Error('project_binding');checks.project_binding=true;
  const result=await invoke('dashboard',{query:{project:'proof',active_only:false,linked:false,offset:0,limit:100}});if(result.tasks.length)throw Error('unexpected_tasks');checks.readonly_dashboard=true;
  const review=await invoke('project_preview',{draft:{...projects[0],max_rounds:4},password:'fixture-private-password',token:null});if(JSON.stringify(review).includes('fixture-private-password'))throw Error('credential_leak');await invoke('project_cancel',{reviewId:review.review_id});checks.preview_redaction=true;
  const session=await invoke('terminal_open',{project:'proof',profile:'shell',task:null,rows:24,cols:80});await invoke('terminal_resize',{session,rows:37,cols:101});await invoke('terminal_write',{session,bytes:Array.from(new TextEncoder().encode("printf 'DESKTOP_PTY_PROOF\\n'; stty size\n"))});
  let output='';const decoder=new TextDecoder();for(let i=0;i<100;i++){for(const event of await invoke('terminal_read',{session})){if(event.type==='data')output+=decoder.decode(new Uint8Array(event.bytes),{stream:true});}if(output.includes('DESKTOP_PTY_PROOF')&&output.includes('37 101'))break;await new Promise(r=>setTimeout(r,30));}if(!output.includes('37 101'))throw Error('pty_io_resize');await invoke('terminal_close',{session});checks.real_webview_ipc_pty=true;
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  const binding=()=>document.querySelector('.terminal-tabs [role="tab"][aria-selected="true"]')?.textContent.replace(/ · (запуск|завершена|ошибка)$/, '')??'Нет сессии';
  const closeActive=()=>document.querySelector('.terminal-tabs [role="tab"][aria-selected="true"]')?.parentElement.querySelector('button[aria-label^="Закрыть"]').click();
  for(let i=0;i<100&&binding()!=='proof · shell';i++)await new Promise(r=>setTimeout(r,30));
  if(binding()!=='proof · shell')throw Error('xterm_session_missing');checks.xterm_connected=true;
  let terminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  if(!terminal)throw Error('smoke_frontend_build_required');
  const renderHost=document.createElement('div');renderHost.style.cssText='position:fixed;left:-10000px;width:800px;height:600px';document.body.appendChild(renderHost);
  const renderer=new terminal.constructor({cols:80,rows:24,scrollback:5000});renderer.open(renderHost);
  let write=bytes=>new Promise(resolve=>renderer.write(bytes,resolve));
  await write('\x1b[?1049h\x1b[2J\x1b[H\x1b[31mRED\x1b[0m');
  if(renderer.buffer.active.type!=='alternate'||renderer.buffer.active.getLine(0).translateToString(true)!=='RED'||renderer.buffer.active.getLine(0).getCell(0).getFgColor()!==1)throw Error('ansi_alternate');
  await write('\x1b[?1049l');checks.ansi_cursor_alternate=true;
  await write('\x1b[2J\x1b[H');const unicode=new TextEncoder().encode('界е\u0301');
  await write(unicode.subarray(0,2));await write(unicode.subarray(2));
  const line=renderer.buffer.active.getLine(0);if(line.getCell(0).getWidth()!==2||line.getCell(2).getChars()!=='е\u0301')throw Error('unicode_cells');checks.unicode_wide_combining=true;
  renderer.select(0,0,3);if(renderer.getSelection()!=='界е\u0301')throw Error('selection');renderer.clearSelection();checks.selection=true;
  renderer.dispose();renderHost.remove();write=bytes=>new Promise(resolve=>terminal.write(bytes,resolve));
  const inputs=[];const listener=terminal.onData(data=>inputs.push(data));
  await write('\x1b[?2004h');terminal.paste('printf BRACKETED_PROOF');listener.dispose();
  if(inputs[0]!=='\x1b[200~printf BRACKETED_PROOF\x1b[201~')throw Error('bracketed_paste');
  // Clear the shell edit buffer before exercising a large ordered paste.
  terminal.input('\x15');terminal.paste("python3 -c \"print('LARGE_PASTE_OK',len('"+'ю'.repeat(12000)+"'))\" ");terminal.input('\r');
  let pastePassed=false;
  for(let i=0;i<300;i++){
   for(let row=0;row<terminal.buffer.active.length;row++)if(terminal.buffer.active.getLine(row).translateToString(true)==='LARGE_PASTE_OK 12000')pastePassed=true;
   if(pastePassed)break;await new Promise(r=>setTimeout(r,20));
  }
  if(!pastePassed)throw Error('large_paste_bytes');checks.large_paste_bytes=true;
  await write('\x1b[?2004l');checks.bracketed_paste=true;
  for(let i=0;i<5100;i++)terminal.writeln('scrollback');await write('');
  if(terminal.buffer.active.length>terminal.rows+5000)throw Error('scrollback_limit');checks.bounded_scrollback=true;
  terminal.clear();
  const terminalMenu=document.querySelector('.toolbar-menu');terminalMenu.querySelector('summary').click();
  const fontSelect=terminalMenu.querySelector('select');fontSelect.value='16';fontSelect.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
  if(terminal.options.fontSize!==16)throw Error('menu_font_size');
  fontSelect.value='14';fontSelect.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
  await write('TOOLBAR_CLEAR_PROOF');
  [...terminalMenu.querySelectorAll('button')].find(b=>b.textContent==='Очистить').click();await new Promise(r=>setTimeout(r,100));
  if(terminalMenu.open||terminal.buffer.active.baseY!==0)throw Error('menu_clear');
  checks.terminal_toolbar_menu=true;
  terminal.focus();checks.large_paste_queued=!document.querySelector('.terminal-pane .error');
  if(!checks.large_paste_queued)throw Error('large_paste_failed');
  const native=[],nativeListener=terminal.onData(data=>native.push(data));
  const trace=[];
  const traceKey=e=>trace.push({type:e.type,key:e.key,keyCode:e.keyCode,data:e.data,inputType:e.inputType,isComposing:e.isComposing,value:terminal.textarea.value});
  const traceTypes=['keydown','keypress','keyup','beforeinput','input','compositionstart','compositionupdate','compositionend'];
  const nativeHost=document.querySelector('.terminal-session:not([hidden]) .terminal-host');
  for(const type of traceTypes)nativeHost.addEventListener(type,traceKey,true);
  terminal.focus();
  const nativeAvailable=await invoke('smoke_native_keyboard');
  await new Promise(r=>setTimeout(r,100));
  nativeListener.dispose();
  for(const type of traceTypes)nativeHost.removeEventListener(type,traceKey,true);
  if(nativeAvailable){
   if(native.join('')!=='отправь задачу'){
    checks.native_keyboard_trace=trace;
    checks.native_keyboard_output=native.join('');
    throw Error('native_russian_keyboard_duplicate');
   }
   checks.native_russian_keyboard=true;
  }
  terminal.input('\x15');
  // Exercise GTK/WebKit's non-composing 229 path with retained textarea text,
  // including overlapping keys before xterm's deferred diff would settle.
  const typed=[],typedListener=terminal.onData(data=>typed.push(data));
  const phrase='отправь задачу Ёж界😀';
  const textarea=terminal.textarea;textarea.value='previously sent text';
  for(const char of phrase){
   textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'Process',keyCode:229,bubbles:true,cancelable:true}));
   textarea.value+=char;
   textarea.dispatchEvent(new InputEvent('input',{inputType:'insertText',data:char,bubbles:true,composed:true}));
   textarea.dispatchEvent(new KeyboardEvent('keyup',{key:'Process',keyCode:229,bubbles:true}));
  }
  await new Promise(r=>setTimeout(r,30));
  typedListener.dispose();
  if(typed.join('')!==phrase)throw Error('unicode_keyboard_duplicate');
  checks.unicode_keyboard_commits_once=true;
  terminal.input('\x15');
  const ibus=[],ibusListener=terminal.onData(data=>ibus.push(data));
  textarea.value='previously sent text';
  for(const char of phrase){
   textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'Unidentified',keyCode:229,bubbles:true,cancelable:true}));
   textarea.value+=char;
   textarea.dispatchEvent(new InputEvent('input',{inputType:'insertFromComposition',data:char,isComposing:true,bubbles:true}));
   textarea.dispatchEvent(new CompositionEvent('compositionend',{data:char,bubbles:true}));
   textarea.dispatchEvent(new KeyboardEvent('keyup',{key:char,keyCode:0,bubbles:true}));
  }
  await new Promise(r=>setTimeout(r,30));
  ibusListener.dispose();
  if(ibus.join('')!==phrase)throw Error('ibus_orphan_composition_duplicate');
  checks.ibus_single_character_commits_once=true;
  terminal.input('\x15');
  const composed=[],composedListener=terminal.onData(data=>composed.push(data));
  textarea.value='';
  textarea.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));
  textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'Process',keyCode:229,isComposing:true,bubbles:true}));
  textarea.dispatchEvent(new CompositionEvent('compositionupdate',{bubbles:true,data:'漢'}));
  textarea.value='漢';
  textarea.dispatchEvent(new InputEvent('input',{inputType:'insertCompositionText',data:'漢',isComposing:true,bubbles:true}));
  await new Promise(r=>setTimeout(r,10));
  textarea.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'漢'}));
  await new Promise(r=>setTimeout(r,30));
  composedListener.dispose();
  if(composed.join('')!=='漢')throw Error('ime_composition_commit');
  checks.ime_composition_preserved=true;
  terminal.input('\x15');
  const keyboard=[];const keyboardListener=terminal.onData(data=>keyboard.push(data));
  terminal.textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'c',code:'KeyC',keyCode:67,ctrlKey:true,bubbles:true}));
  keyboardListener.dispose();if(!keyboard.includes('\x03'))throw Error('ctrl_c');checks.keyboard_sigint=true;
  await write('\x1b[?1000h\x1b[?1006h');
  const mouse=[];const mouseListener=terminal.onData(data=>mouse.push(data));
  const screen=document.querySelector('.xterm-screen'),rect=screen.getBoundingClientRect();
  screen.dispatchEvent(new MouseEvent('mousedown',{button:0,buttons:1,clientX:rect.left+10,clientY:rect.top+10,bubbles:true}));
  document.dispatchEvent(new MouseEvent('mouseup',{button:0,buttons:0,clientX:rect.left+10,clientY:rect.top+10,bubbles:true}));
  mouseListener.dispose();await write('\x1b[?1000l\x1b[?1006l');
  if(!mouse.some(data=>data.startsWith('\x1b[<')))throw Error('mouse_sgr');checks.mouse_reporting=true;
  await invoke('clipboard_write',{text:'CLIPBOARD_界е\u0301'});
  if(await invoke('clipboard_read')!=='CLIPBOARD_界е\u0301')throw Error('clipboard_roundtrip');checks.native_clipboard_unicode=true;
  const xterm=document.querySelector('.xterm');if(!xterm)throw Error('xterm_missing');
  const separator=document.querySelector('[role="separator"]'),before=separator.getAttribute('aria-valuenow');separator.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));await new Promise(r=>setTimeout(r,100));if(separator.getAttribute('aria-valuenow')===before)throw Error('split_unchanged');checks.split_keyboard=true;
  const settings=[...document.querySelectorAll('nav button')].find(b=>b.getAttribute('aria-label')==='Настройки');settings.click();await new Promise(r=>setTimeout(r,100));if(!document.querySelector('input[type="password"]'))throw Error('settings_missing');checks.settings_rendered=true;
  if(document.querySelector('.xterm')!==xterm||binding()!=='proof · shell')throw Error('terminal_recreated_on_rerender');checks.terminal_survives_rerender=true;
  const waitUI=async(check,label)=>{for(let i=0;i<150;i++){if(await check())return;await new Promise(r=>setTimeout(r,30));}throw Error(label);};
  const branchSelect=document.querySelector('[aria-label="Ветка Git проекта"]');
  await waitUI(()=>branchSelect.value==='refs/heads/main'&&branchSelect.querySelector('option[value="refs/heads/feature"]'),'project_branches_missing');
  const chooseBranch=reference=>{branchSelect.value=reference;branchSelect.dispatchEvent(new Event('change',{bubbles:true}));};
  const switchBranch=async(reference)=>{chooseBranch(reference);await waitUI(()=>[...document.querySelectorAll('.project-branches button')].some(b=>b.getAttribute('aria-label')==='Переключить'),'branch_switch_missing');[...document.querySelectorAll('.project-branches button')].find(b=>b.getAttribute('aria-label')==='Переключить').click();await waitUI(async()=>(await invoke('project_branches',{project:'proof'})).current===reference,'branch_switch_failed');await waitUI(()=>!document.querySelector('.project-branches button[aria-label="Переключение…"]'),'branch_switch_busy');};
  await switchBranch('refs/heads/feature');await switchBranch('refs/heads/main');
  if(document.querySelector('.xterm')!==xterm||binding()!=='proof · shell')throw Error('branch_switch_recreated_pty');
  checks.project_git_branches=true;checks.project_git_switch=true;
  const setInput=(label,value)=>{const input=document.querySelector(`[aria-label="${label}"]`);if(!input)throw Error('missing_'+label);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
  document.querySelector('.project-branches button[aria-label="Git"]').click();
  await waitUI(()=>document.querySelector('.git-dialog').open,'git_menu_missing');
  const gitButton=text=>[...document.querySelectorAll('.git-dialog button')].find(b=>b.textContent===text);
  const gitIdle=()=>!document.querySelector('.git-dialog fieldset').disabled;
  setInput('Имя новой ветки','ui-topic');await new Promise(r=>setTimeout(r,50));gitButton('Создать ветку').click();
  await waitUI(async()=>(await invoke('project_branches',{project:'proof'})).current==='refs/heads/ui-topic','git_create_failed');
  await waitUI(gitIdle,'git_create_busy');
  setInput('Ветка назначения push','ui-topic');await new Promise(r=>setTimeout(r,50));gitButton('Просмотреть push').click();
  await waitUI(()=>document.querySelector('[aria-label="Параметры push"]'),'git_preview_missing');
  const pushPreview=document.querySelector('[aria-label="Параметры push"]');
  if(!pushPreview.textContent.includes('origin → ui-topic')||!pushPreview.textContent.includes('Коммитов к отправке: 1'))throw Error('git_preview_parameters');
  const beforePush=await invoke('project_branches',{project:'proof'});if(beforePush.upstream)throw Error('git_preview_changed_upstream');
  await waitUI(()=>!gitButton('Отправить').disabled,'git_preview_busy');gitButton('Отправить').click();
  await waitUI(()=>document.querySelector('.git-dialog').textContent.includes('Коммиты отправлены'),'git_push_failed');
  const afterPush=await invoke('project_branches',{project:'proof'});if(afterPush.upstream?.remote!=='origin'||afterPush.upstream?.destination!=='ui-topic')throw Error('git_push_upstream');
  await waitUI(gitIdle,'git_push_busy');gitButton('Fetch').click();
  await waitUI(()=>document.querySelector('.git-dialog').textContent.includes('Удалённые ветки обновлены'),'git_fetch_failed');
  await waitUI(gitIdle,'git_fetch_busy');
  if(!(await invoke('project_branches',{project:'proof'})).branches.some(b=>b.reference==='refs/remotes/origin/ui-topic'))throw Error('git_fetch_branches');
  gitButton('Закрыть').click();await waitUI(()=>!document.querySelector('.git-dialog').open,'git_menu_close');await switchBranch('refs/heads/main');
  if(document.querySelector('.xterm')!==xterm||binding()!=='proof · shell')throw Error('git_actions_recreated_pty');
  checks.project_git_create=true;checks.project_git_preview_push=true;checks.project_git_fetch=true;

  await waitUI(()=>document.querySelector('.project-indicator')&&!document.querySelector('.project-indicator-checking'),'project_status_not_loaded');
  if(document.querySelector('.project-indicator-running')||!document.querySelector('.project-indicator').getAttribute('aria-label').includes('proof'))throw Error('project_status_binding');checks.project_status_indicator=true;
  await waitUI(()=>document.querySelector('.project-select option[value="proof"]').textContent.includes('остановлен'),'project_list_stopped_status');checks.project_list_service_status=true;
  const remoteToggle=[...document.querySelectorAll('.settings label.check')].find(label=>label.textContent.includes('Запуск OpenCode на другом ПК')).querySelector('input');
  if(remoteToggle.checked||document.querySelector('[aria-label="host"]'))throw Error('remote_not_default_off');
  remoteToggle.click();await waitUI(()=>document.querySelector('[aria-label="host"]'),'remote_fields_missing');
  for(const [key,value] of Object.entries({host:'192.0.2.1',user:'executor',project:'proof',executable:'/opt/bridge/agent-bridge',config:'/home/executor/projects.toml',state_root:'/home/executor/state',repository:'git@gitlab.example:owner/repo.git'}))setInput(key,value);
  await new Promise(r=>setTimeout(r,50));document.querySelector('.settings form').requestSubmit();
  await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'remote_preview_missing');
  if(!document.querySelector('[aria-label="Просмотр изменений"]').textContent.includes('192.0.2.1'))throw Error('remote_preview_missing_binding');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Отмена').click();
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'remote_preview_cancel');
  remoteToggle.click();await waitUI(()=>!document.querySelector('[aria-label="host"]'),'remote_toggle_off');
  if((await invoke('projects'))[0].remote_execution)throw Error('remote_preview_wrote_configuration');checks.remote_execution_opt_in_preview=true;
  setInput('Модель исполнителя OpenCode','fixture/executor');setInput('Модель контроллера OpenCode','fixture/controller');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();
  await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'model_preview_missing');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(async()=>{const p=(await invoke('projects'))[0];return p.opencode_model==='fixture/executor'&&p.opencode_controller_model==='fixture/controller';},'models_not_saved');
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'model_review_still_open');
  await new Promise(r=>setTimeout(r,100));
  setInput('Модель исполнителя OpenCode','');setInput('Модель контроллера OpenCode','');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'model_clear_preview');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(async()=>{const p=(await invoke('projects'))[0];return p.opencode_model===null&&p.opencode_controller_model===null;},'models_not_cleared');
  checks.project_models_settings=true;
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'model_clear_review_still_open');
  await new Promise(r=>setTimeout(r,150));
  const baseline=(await invoke('projects'))[0];
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'retry_preview_missing');
  let externalReview=await invoke('project_preview',{draft:{...baseline,max_rounds:baseline.max_rounds+1},password:null,token:null});
  await invoke('project_apply',{reviewId:externalReview.review_id});
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>document.querySelector('.settings .error'),'save_error_missing');
  externalReview=await invoke('project_preview',{draft:baseline,password:null,token:null});await invoke('project_apply',{reviewId:externalReview.review_id});
  await waitUI(()=>![...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').disabled,'retry_still_busy');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'retry_not_saved');
  if(document.querySelector('.settings .error'))throw Error('successful_save_retained_old_error');checks.successful_save_clears_error=true;

  await waitUI(()=>document.querySelector('.opencode-keys form'),'provider_keys_missing');
  setInput('Имя переменной провайдера','PROVIDER_API_KEY');setInput('Значение ключа провайдера','fixture-provider-secret');await new Promise(r=>setTimeout(r,50));
  if(document.querySelector('[aria-label="Значение ключа провайдера"]').type!=='password')throw Error('provider_key_not_masked');
  document.querySelector('.opencode-keys form').requestSubmit();
  await waitUI(()=>document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]'),'provider_key_not_saved');
  const keyView=await invoke('opencode_keys_read',{project:'proof'});
  if(keyView.names.join(',')!=='PROVIDER_API_KEY'||JSON.stringify(keyView).includes('fixture-provider-secret')||document.querySelector('[aria-label="Значение ключа провайдера"]').value)throw Error('provider_key_leak');
  await waitUI(()=>document.querySelector('[aria-label="Env-файл исполнителя OpenCode"]').value===keyView.file,'provider_env_not_bound_in_form');
  [...document.querySelectorAll('.opencode-keys button')].find(b=>b.textContent==='Заменить').click();
  setInput('Значение ключа провайдера','fixture-provider-replaced');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.opencode-keys form').requestSubmit();await waitUI(()=>!document.querySelector('[aria-label="Значение ключа провайдера"]').value,'provider_key_not_replaced');
  document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]').click();
  await waitUI(()=>!document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]'),'provider_key_not_deleted');
  if((await invoke('opencode_keys_read',{project:'proof'})).names.length)throw Error('provider_key_still_present');
  checks.provider_keys_ui=true;checks.provider_keys_redacted=true;

  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Загрузить').click();
  await waitUI(()=>document.querySelector('[aria-label="Содержимое конфигурации OpenCode"]'),'config_editor_missing');
  const editor=document.querySelector('[aria-label="Содержимое конфигурации OpenCode"]');
  const edited='{\n  "$schema": "https://opencode.ai/config.json",\n  "instructions": []\n}\n';
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(editor,edited);editor.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,50));
  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Проверить конфигурацию OpenCode').click();
  await waitUI(()=>document.querySelector('[aria-label="Просмотр конфигурации OpenCode"]'),'config_editor_preview_missing');
  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Сохранить конфигурацию OpenCode').click();
  await waitUI(()=>document.querySelector('.opencode-editor [role="status"]'),'config_editor_save_failed');
  const editedFile=await invoke('opencode_config_read',{project:'proof',file:'opencode.json'});if(editedFile.content!==edited)throw Error('config_editor_bytes');
  checks.opencode_project_editor=true;

  document.querySelector('nav button').click();await new Promise(r=>setTimeout(r,100));
  const bufferText=t=>Array.from({length:t.buffer.active.length},(_,i)=>t.buffer.active.getLine(i).translateToString(true)).join('\n');
  const waitFor=async(check,label)=>{for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,30));}throw Error(label);};
  terminal.input('\x15');terminal.paste("export TAB_MARKER=first; printf 'FIRST_TAB_READY\\n'");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('FIRST_TAB_READY'),'first_tab_ready');
  const firstTab=document.querySelector('[role="tab"][aria-selected="true"]');
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  await waitFor(()=>document.querySelectorAll('.terminal-session').length===2,'second_tab_missing');
  const secondTab=document.querySelector('[role="tab"][aria-selected="true"]');
  const secondTerminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  await waitFor(()=>!secondTab.textContent.includes(' · запуск')&&bufferText(secondTerminal).trim().length>0,'second_tab_not_ready');
  if(secondTerminal===terminal||!terminal.element.closest('[hidden]'))throw Error('first_tab_replaced');
  terminal.paste("printf 'BACKGROUND_TAB_ALIVE\\n'");terminal.input('\r');
  secondTerminal.paste("printf 'SECOND_TAB:%s\\n' ${TAB_MARKER:-independent}");secondTerminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('BACKGROUND_TAB_ALIVE')&&bufferText(secondTerminal).split('\n').includes('SECOND_TAB:independent'),'tab_process_isolation');
  secondTerminal.paste("trap '' TERM; echo STOP_CONSOLE_PID:$$; sleep 90 & echo STOP_CHILD_PID:$!; wait");secondTerminal.input('\r');
  await waitFor(()=>/STOP_CONSOLE_PID:\d+/.test(bufferText(secondTerminal))&&/STOP_CHILD_PID:\d+/.test(bufferText(secondTerminal)),'stop_console_pids');
  const stoppedPids=[...bufferText(secondTerminal).matchAll(/STOP_(?:CONSOLE|CHILD)_PID:(\d+)/g)].map(match=>Number(match[1]));
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Завершить консоль').click();
  await waitFor(()=>secondTab.textContent.includes(' · завершена'),'stop_console_status');
  if(!bufferText(secondTerminal).includes('SECOND_TAB:independent')||!bufferText(secondTerminal).includes('[консоль завершена пользователем]'))throw Error('stop_console_lost_output');
  if(document.querySelectorAll('.terminal-session').length!==2)throw Error('stop_console_removed_tab');
  checks.console_stop_preserves_output=true;
  firstTab.click();await new Promise(r=>setTimeout(r,100));
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==terminal)throw Error('tab_buffer_replaced');
  secondTab.parentElement.querySelector('button[aria-label^="Закрыть"]').click();
  await waitFor(()=>document.querySelectorAll('.terminal-session').length===1,'tab_close_missing');
  terminal.paste("printf 'SURVIVING_TAB:%s\\n' $TAB_MARKER");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('SURVIVING_TAB:first'),'closing_tab_killed_peer');
  terminal.paste("if "+stoppedPids.map(pid=>"kill -0 "+pid+" 2>/dev/null").join(' || ')+"; then echo STOP_TREE_LEAK; else echo STOP_TREE_CLEAN; fi");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('STOP_TREE_CLEAN'),'stop_console_tree_leaked');
  checks.console_stop_kills_process_tree=true;
  terminalMenu.querySelector('summary').click();
  [...terminalMenu.querySelectorAll('button')].find(b=>b.textContent==='Остановить сервер OpenCode проекта').click();
  await waitFor(()=>document.querySelector('.terminal-pane [role="status"]')?.textContent==='Сервер OpenCode уже остановлен','stop_server_noop_feedback');
  if(terminalMenu.open)throw Error('stop_server_menu_remains_open');
  checks.opencode_server_stop_feedback=true;
  checks.independent_terminal_tabs=true;checks.background_tab_output=true;checks.tab_close_preserves_peer=true;

  const proofTerminal=terminal,proofTab=document.querySelector('[role="tab"][aria-selected="true"]');
  const otherWorkspace=projects[0].workspace.slice(0,projects[0].workspace.lastIndexOf('/'))+'/other';
  const quote=value=>"'"+value.replaceAll("'","'\\''")+"'";
  terminal.input('\x15');terminal.paste("mkdir -p "+quote(otherWorkspace)+"; printf 'OTHER_WORKSPACE_READY\\n'");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('OTHER_WORKSPACE_READY'),'other_workspace_missing');
  [...document.querySelectorAll('nav button')].find(b=>b.getAttribute('aria-label')==='Настройки').click();
  await waitUI(()=>document.querySelector('.settings'),'other_project_settings');
  [...document.querySelectorAll('.settings button')].find(b=>b.textContent==='Клонировать').click();await new Promise(r=>setTimeout(r,50));
  const editField=(input,value)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
  editField(document.querySelector('.settings input[pattern]'),'other');
  editField(document.querySelector('.settings form .input-action input'),otherWorkspace);await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'other_project_preview');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>document.querySelector('.project-select option[value="other"]'),'other_project_not_saved');
  document.querySelector('nav button').click();
  const selectProject=value=>{const select=document.querySelector('.project-select select');select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));};
  proofTerminal.input('\x15');proofTerminal.paste("sleep 1; printf 'PROJECT_BACKGROUND_OUTPUT\\n'");proofTerminal.input('\r');
  selectProject('other');await waitFor(()=>binding()==='Нет сессии','other_showed_proof_terminal');
  if(document.querySelectorAll('.terminal-tabs [role="tab"]').length||document.querySelector('.terminal-session:not([hidden])'))throw Error('foreign_terminal_visible');
  await waitFor(()=>document.querySelector('.dashboard')?.getAttribute('aria-label')==='Задачи проекта other','other_dashboard_binding');
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  await waitFor(()=>binding()==='other · shell','other_terminal_not_opened');
  const otherTerminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  await waitFor(()=>!document.querySelector('[role="tab"][aria-selected="true"]').textContent.includes(' · запуск')&&bufferText(otherTerminal).includes('$'),'other_pty_not_ready');
  otherTerminal.paste("export TAB_MARKER=other; printf 'OTHER_PROJECT_READY\\n'");otherTerminal.input('\r');
  await waitFor(()=>bufferText(otherTerminal).split('\n').includes('OTHER_PROJECT_READY'),'other_terminal_not_ready');
  const programSelect=document.querySelector('[aria-label="Программа терминала"]');programSelect.value='codex';programSelect.dispatchEvent(new Event('change',{bubbles:true}));
  selectProject('proof');await waitFor(()=>binding()==='proof · shell','proof_active_tab_lost');
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==proofTerminal||document.querySelector('[role="tab"][aria-selected="true"]').id!==proofTab.id)throw Error('project_switch_recreated_terminal');
  if(document.querySelector('[aria-label="Программа терминала"]').value!=='shell'||document.querySelectorAll('.terminal-tabs [role="tab"]').length!==1)throw Error('project_terminal_controls_leaked');
  await waitFor(()=>bufferText(proofTerminal).split('\n').includes('PROJECT_BACKGROUND_OUTPUT'),'hidden_project_output_lost');
  proofTerminal.paste("printf 'PROJECT_SURVIVED:%s\\n' $TAB_MARKER");proofTerminal.input('\r');
  await waitFor(()=>bufferText(proofTerminal).split('\n').includes('PROJECT_SURVIVED:first'),'switching_project_killed_pty');
  closeActive();
  selectProject('other');await waitFor(()=>binding()==='other · shell','closing_proof_killed_other');
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==otherTerminal||document.querySelector('[aria-label="Программа терминала"]').value!=='codex')throw Error('other_project_state_lost');
  otherTerminal.paste("printf 'OTHER_SURVIVED:%s\\n' $TAB_MARKER");otherTerminal.input('\r');
  await waitFor(()=>bufferText(otherTerminal).split('\n').includes('OTHER_SURVIVED:other'),'other_project_process_stopped');
  closeActive();
  selectProject('proof');await waitFor(()=>document.querySelector('.dashboard')?.getAttribute('aria-label')==='Задачи проекта proof','proof_dashboard_not_restored');
  await waitUI(()=>['proof','other'].every(id=>{const text=document.querySelector(`.project-select option[value="${id}"]`)?.textContent;return text&&text.includes('остановлен');}),'all_project_list_statuses');
  checks.project_workspace_isolation=true;checks.project_switch_preserves_pty=true;checks.project_dashboard_scope=true;
  closeActive();
  const program=document.querySelector('[aria-label="Программа терминала"]');program.value='codex';program.dispatchEvent(new Event('change',{bubbles:true}));
  await waitUI(()=>document.querySelector('[aria-label="Переменные окружения Codex"]')&&!document.querySelector('[aria-label="Переменные окружения Codex"]').disabled,'codex_env_not_loaded');
  document.querySelector('.terminal-launch-env').open=true;
  const envField=document.querySelector('[aria-label="Переменные окружения Codex"]');
  const envText='export AIBRIDGE_TEST_ENV="project value"\n';
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(envField,envText);envField.dispatchEvent(new Event('input',{bubbles:true}));
  await waitUI(()=>!document.querySelector('.terminal-launch-env button').disabled,'codex_env_not_dirty');
  document.querySelector('.terminal-launch-env button').click();
  await waitUI(async()=>await invoke('codex_env_read',{project:'proof'})===envText,'codex_env_not_persisted');
  await waitUI(()=>document.querySelector('.terminal-launch-env .muted').textContent==='Сохранено для проекта','codex_env_status');
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(envField,'');envField.dispatchEvent(new Event('input',{bubbles:true}));
  await waitUI(()=>!document.querySelector('.terminal-launch-env button').disabled,'codex_env_clear_not_dirty');document.querySelector('.terminal-launch-env button').click();
  await waitUI(async()=>await invoke('codex_env_read',{project:'proof'})==='','codex_env_not_cleared');checks.codex_environment_persistence=true;
  [...document.querySelectorAll('nav button')].find(b=>b.getAttribute('aria-label')==='Автоматизация').click();
  await waitUI(()=>document.querySelector('[aria-label="JSON-план автоматизации"]'),'automation_tab_missing');
  const plan={version:1,goal:'Smoke approved goal',steps:[{id:'one',task:'Create file',allowed_paths:['file.txt'],test_commands:['true'],acceptance_criteria:['File exists']}],final_test_commands:['true'],delivery:'manual'};
  const planField=document.querySelector('[aria-label="JSON-план автоматизации"]');
  const setPlan=text=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(planField,text);planField.dispatchEvent(new Event('input',{bubbles:true}));};
  const checkButton=()=>[...document.querySelectorAll('.automation button')].find(b=>b.textContent==='Проверить план');
  setPlan(JSON.stringify(plan));await waitUI(()=>checkButton()&&!checkButton().disabled,'automation_preview_not_ready');checkButton().click();
  await waitUI(()=>document.querySelector('[aria-label="Согласование плана"]'),'automation_preview_missing');
  if(!document.querySelector('[aria-label="Согласование плана"]').textContent.includes('Smoke approved goal')||![...document.querySelectorAll('.automation button')].some(b=>b.textContent==='Утвердить и запустить'&&!b.disabled))throw Error('automation_approval_missing');
  setPlan(JSON.stringify({...plan,goal:'Changed goal'}));
  await waitUI(()=>!document.querySelector('[aria-label="Согласование плана"]'),'automation_stale_approval');
  checkButton().click();await waitUI(()=>document.querySelector('[aria-label="Согласование плана"]'),'automation_repreview_missing');
  [...document.querySelectorAll('.automation .review button')].find(b=>b.textContent==='Отменить').click();
  await waitUI(()=>!document.querySelector('[aria-label="Согласование плана"]'),'automation_cancel_failed');
  setPlan('{}');await waitUI(()=>checkButton()&&!checkButton().disabled,'automation_invalid_preview_busy');checkButton().click();
  await waitUI(()=>document.querySelector('.automation [role="alert"]'),'automation_invalid_plan_no_error');
  if(document.querySelector('[aria-label="Согласование плана"]'))throw Error('automation_invalid_plan_approved');
  checks.automation_plan_preview_and_invalidation=true;checks.automation_invalid_plan_refused=true;
  [...document.querySelectorAll('nav button')].find(b=>b.getAttribute('aria-label')==='Dashboard').click();
  const options=await invoke('smoke_options');
  if(options.live_tui){
   for(const profile of ['codex','opencode']){
    const select=document.querySelector('[aria-label="Программа терминала"]');select.value=profile;select.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,50));
    [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
    await new Promise(r=>setTimeout(r,100));
    terminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
    let ready=false;
    for(let i=0;i<600;i++){
     let text='';for(let row=0;row<terminal.buffer.active.length;row++)text+=terminal.buffer.active.getLine(row).translateToString(true)+'\n';
     if(binding()===`proof · ${profile}`&&new RegExp(profile==='codex'?'codex|OpenAI|trust':'opencode|OpenCode|Trust','i').test(text)){ready=true;break;}
     await new Promise(r=>setTimeout(r,50));
    }
    if(!ready)throw Error(profile+'_tui_missing');
    if(profile==='codex'){
     const keys=[],keyListener=terminal.onData(data=>keys.push(data));
     terminal.focus();
     const available=await invoke('smoke_native_keyboard');
     await new Promise(r=>setTimeout(r,100));keyListener.dispose();
     if(available&&keys.join('')!=='отправь задачу')throw Error('codex_native_keyboard_duplicate');
     if(available)checks.codex_native_russian_keyboard=true;
     terminal.input('\x15');
    }
    terminal.input('\x1b[B');terminal.input('\t');
    const size=document.querySelector('[aria-label="Размер шрифта терминала"]');size.value='16';size.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
    if(!document.querySelector('.xterm')||binding()!==`proof · ${profile}`)throw Error(profile+'_tui_resize');
    checks[profile+'_actual_tui_render_input_resize']=true;
    if(profile==='opencode'){
     if(document.querySelectorAll('.terminal-session').length!==2)throw Error('controller_tabs_missing');
     closeActive();await new Promise(r=>setTimeout(r,800));
     if(binding()!=='proof · codex')throw Error('codex_stopped_by_opencode');
     checks.codex_opencode_coexist=true;
     closeActive();await new Promise(r=>setTimeout(r,800));
    }
   }
  }
  selectProject('other');
  [...document.querySelectorAll('nav button')].find(b=>b.getAttribute('aria-label')==='Настройки').click();
  await waitUI(()=>document.querySelector('[aria-label="Удаление проекта"]'),'project_remove_button_missing');
  const removeButton=()=>[...document.querySelectorAll('[aria-label="Удаление проекта"] button')].find(b=>b.textContent==='Удалить проект');
  removeButton().click();await waitUI(()=>document.querySelector('[aria-label="Подтверждение удаления проекта"]'),'project_remove_preview_missing');
  if(!document.querySelector('[aria-label="Подтверждение удаления проекта"]').textContent.includes('other'))throw Error('project_remove_wrong_binding');
  [...document.querySelectorAll('[aria-label="Подтверждение удаления проекта"] button')].find(b=>b.textContent==='Отмена').click();
  await waitUI(()=>!document.querySelector('[aria-label="Подтверждение удаления проекта"]'),'project_remove_cancel_failed');
  if(!(await invoke('projects')).some(p=>p.id==='other'))throw Error('project_remove_cancel_mutated_config');
  removeButton().click();await waitUI(()=>document.querySelector('[aria-label="Подтверждение удаления проекта"]'),'project_remove_second_preview_missing');
  [...document.querySelectorAll('[aria-label="Подтверждение удаления проекта"] button')].find(b=>b.textContent==='Подтвердить удаление').click();
  await waitUI(()=>!document.querySelector('.project-select option[value="other"]'),'project_remove_list_not_updated');
  if(!(await invoke('projects')).some(p=>p.id==='proof'))throw Error('project_remove_deleted_other_project');
  checks.project_removal_preview_cancel_apply=true;
  if(!options.live_tui){
   selectProject('proof');
   const profileSelect=document.querySelector('[aria-label="Программа терминала"]');profileSelect.value='opencode';profileSelect.dispatchEvent(new Event('change',{bubbles:true}));
   await new Promise(r=>setTimeout(r,50));
   [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
   await waitUI(()=>document.querySelector('.terminal-tabs [aria-selected="true"]')?.textContent.includes('opencode · завершена'),'failed_opencode_console_exit');
   const failedTerminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
   const pid=bufferText(failedTerminal).match(/FAILED_CONSOLE_SERVER_PID:(\d+)/)?.[1];
   if(!pid)throw Error('failed_opencode_daemon_missing');
   const stopButton=[...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Завершить OpenCode');
   if(!stopButton||stopButton.disabled)throw Error('failed_opencode_stop_button_disabled');
   stopButton.click();
   try{await waitUI(()=>document.querySelector('.terminal-pane [role="status"]')?.textContent==='Сервер OpenCode остановлен','failed_opencode_stop_no_feedback');}
   catch(e){checks.stop_error=document.querySelector('.terminal-pane [role="alert"]')?.textContent;checks.stop_status=document.querySelector('.terminal-pane [role="status"]')?.textContent;checks.stop_button=stopButton.textContent;throw e;}
   if(!bufferText(failedTerminal).includes('[процесс завершён: 1]'))throw Error('failed_opencode_output_lost');
   const proof=await invoke('terminal_open',{project:'proof',profile:'shell',task:null,rows:24,cols:80});
   await invoke('terminal_write',{session:proof,bytes:Array.from(new TextEncoder().encode(`if kill -0 ${pid} 2>/dev/null; then echo OPENCODE_STOP_LEAK; else echo OPENCODE_STOP_CLEAN; fi\n`))});
   let output='';
   await waitUI(async()=>{for(const event of await invoke('terminal_read',{session:proof}))if(event.type==='data')output+=new TextDecoder().decode(new Uint8Array(event.bytes));return output.split(/[\r\n]+/).includes('OPENCODE_STOP_CLEAN');},'failed_opencode_daemon_alive');
   await invoke('terminal_close',{session:proof});
   checks.failed_opencode_stop_button_enabled=true;checks.failed_opencode_stop_kills_server=true;
  }
  const exitSession=await invoke('terminal_open',{project:'proof',profile:'shell',task:null,rows:24,cols:80});
  await invoke('terminal_write',{session:exitSession,bytes:Array.from(new TextEncoder().encode("trap '' TERM; echo EXIT_PARENT:$$; sleep 90 & echo EXIT_CHILD:$!; wait\n"))});
  let exitOutput='';
  for(let i=0;i<100;i++) {
    for(const event of await invoke('terminal_read',{session:exitSession})) if(event.type==='data')exitOutput+=new TextDecoder().decode(new Uint8Array(event.bytes));
    const parent=exitOutput.match(/EXIT_PARENT:(\d+)/),child=exitOutput.match(/EXIT_CHILD:(\d+)/);
    if(parent&&child){checks.exit_processes=[Number(parent[1]),Number(child[1])];break;}
    await new Promise(r=>setTimeout(r,30));
  }
  if(!checks.exit_processes)throw Error('exit_process_proof_missing');
  await invoke('smoke_complete',{passed:true,checks});
 }catch(error){checks.failure=error.message;await invoke('smoke_complete',{passed:false,checks});}
})();
