(async()=>{
 const invoke=window.__TAURI_INTERNALS__.invoke;
 const checks={};
 try {
  for(let i=0;i<100&&!document.querySelector('.brand');i++)await new Promise(r=>setTimeout(r,50));
  if(!document.querySelector('.brand'))throw Error('frontend_missing');checks.react_rendered=true;
  const projects=await invoke('projects');if(projects.length!==1||projects[0].id!=='proof')throw Error('project_binding');checks.project_binding=true;
  const result=await invoke('dashboard',{query:{project:'proof',active_only:false,linked:false,offset:0,limit:100}});if(result.tasks.length)throw Error('unexpected_tasks');checks.readonly_dashboard=true;
  const review=await invoke('project_preview',{draft:{...projects[0],max_rounds:4},password:'fixture-private-password',token:null});if(JSON.stringify(review).includes('fixture-private-password'))throw Error('credential_leak');await invoke('project_cancel',{reviewId:review.review_id});checks.preview_redaction=true;
  const session=await invoke('terminal_open',{project:'proof',profile:'shell',task:null,rows:24,cols:80});await invoke('terminal_resize',{session,rows:37,cols:101});await invoke('terminal_write',{session,bytes:Array.from(new TextEncoder().encode("printf 'DESKTOP_PTY_PROOF\\n'; stty size\n"))});
  let output='';const decoder=new TextDecoder();for(let i=0;i<100;i++){for(const event of await invoke('terminal_read',{session})){if(event.type==='data')output+=decoder.decode(new Uint8Array(event.bytes),{stream:true});}if(output.includes('DESKTOP_PTY_PROOF')&&output.includes('37 101'))break;await new Promise(r=>setTimeout(r,30));}if(!output.includes('37 101'))throw Error('pty_io_resize');await invoke('terminal_close',{session});checks.real_webview_ipc_pty=true;
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  const binding=()=>document.querySelector('.terminal-tabs [role="tab"][aria-selected="true"]')?.textContent.replace(/ · (запуск|завершена|ошибка)$/, '')??'Нет сессии';
  const closeActive=()=>document.querySelector('.terminal-tabs [role="tab"][aria-selected="true"]')?.parentElement.querySelector('button[aria-label^="Закрыть"]').click();
  for(let i=0;i<100&&binding()!=='proof · shell';i++)await new Promise(r=>setTimeout(r,30));
  if(binding()!=='proof · shell')throw Error('xterm_session_missing');checks.xterm_connected=true;
  let terminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  if(!terminal)throw Error('smoke_frontend_build_required');
  const renderHost=document.createElement('div');renderHost.style.cssText='position:fixed;left:-10000px;width:800px;height:600px';document.body.appendChild(renderHost);
  const renderer=new terminal.constructor({cols:80,rows:24,scrollback:5000});renderer.open(renderHost);
  let write=bytes=>new Promise(resolve=>renderer.write(bytes,resolve));
  await write('\x1b[?1049h\x1b[2J\x1b[H\x1b[31mRED\x1b[0m');
  if(renderer.buffer.active.type!=='alternate'||renderer.buffer.active.getLine(0).translateToString(true)!=='RED'||renderer.buffer.active.getLine(0).getCell(0).getFgColor()!==1)throw Error('ansi_alternate');
  await write('\x1b[?1049l');checks.ansi_cursor_alternate=true;
  await write('\x1b[2J\x1b[H');const unicode=new TextEncoder().encode('界е\u0301');
  await write(unicode.subarray(0,2));await write(unicode.subarray(2));
  const line=renderer.buffer.active.getLine(0);if(line.getCell(0).getWidth()!==2||line.getCell(2).getChars()!=='е\u0301')throw Error('unicode_cells');checks.unicode_wide_combining=true;
  renderer.select(0,0,3);if(renderer.getSelection()!=='界е\u0301')throw Error('selection');renderer.clearSelection();checks.selection=true;
  renderer.dispose();renderHost.remove();write=bytes=>new Promise(resolve=>terminal.write(bytes,resolve));
  const inputs=[];const listener=terminal.onData(data=>inputs.push(data));
  await write('\x1b[?2004h');terminal.paste('printf BRACKETED_PROOF');listener.dispose();
  if(inputs[0]!=='\x1b[200~printf BRACKETED_PROOF\x1b[201~')throw Error('bracketed_paste');
  // Clear the shell edit buffer before exercising a large ordered paste.
  terminal.input('\x15');terminal.paste("python3 -c \"print('LARGE_PASTE_OK',len('"+'ю'.repeat(12000)+"'))\" ");terminal.input('\r');
  let pastePassed=false;
  for(let i=0;i<300;i++){
   for(let row=0;row<terminal.buffer.active.length;row++)if(terminal.buffer.active.getLine(row).translateToString(true)==='LARGE_PASTE_OK 12000')pastePassed=true;
   if(pastePassed)break;await new Promise(r=>setTimeout(r,20));
  }
  if(!pastePassed)throw Error('large_paste_bytes');checks.large_paste_bytes=true;
  await write('\x1b[?2004l');checks.bracketed_paste=true;
  for(let i=0;i<5100;i++)terminal.writeln('scrollback');await write('');
  if(terminal.buffer.active.length>terminal.rows+5000)throw Error('scrollback_limit');checks.bounded_scrollback=true;
  terminal.clear();
  const terminalMenu=document.querySelector('.toolbar-menu');terminalMenu.querySelector('summary').click();
  const fontSelect=terminalMenu.querySelector('select');fontSelect.value='16';fontSelect.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
  if(terminal.options.fontSize!==16)throw Error('menu_font_size');
  fontSelect.value='14';fontSelect.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
  await write('TOOLBAR_CLEAR_PROOF');
  [...terminalMenu.querySelectorAll('button')].find(b=>b.textContent==='Очистить').click();await new Promise(r=>setTimeout(r,100));
  if(terminalMenu.open||terminal.buffer.active.baseY!==0)throw Error('menu_clear');
  checks.terminal_toolbar_menu=true;
  terminal.focus();checks.large_paste_queued=!document.querySelector('.terminal-pane .error');
  if(!checks.large_paste_queued)throw Error('large_paste_failed');
  const keyboard=[];const keyboardListener=terminal.onData(data=>keyboard.push(data));
  terminal.textarea.dispatchEvent(new KeyboardEvent('keydown',{key:'c',code:'KeyC',keyCode:67,ctrlKey:true,bubbles:true}));
  keyboardListener.dispose();if(!keyboard.includes('\x03'))throw Error('ctrl_c');checks.keyboard_sigint=true;
  await write('\x1b[?1000h\x1b[?1006h');
  const mouse=[];const mouseListener=terminal.onData(data=>mouse.push(data));
  const screen=document.querySelector('.xterm-screen'),rect=screen.getBoundingClientRect();
  screen.dispatchEvent(new MouseEvent('mousedown',{button:0,buttons:1,clientX:rect.left+10,clientY:rect.top+10,bubbles:true}));
  document.dispatchEvent(new MouseEvent('mouseup',{button:0,buttons:0,clientX:rect.left+10,clientY:rect.top+10,bubbles:true}));
  mouseListener.dispose();await write('\x1b[?1000l\x1b[?1006l');
  if(!mouse.some(data=>data.startsWith('\x1b[<')))throw Error('mouse_sgr');checks.mouse_reporting=true;
  await invoke('clipboard_write',{text:'CLIPBOARD_界е\u0301'});
  if(await invoke('clipboard_read')!=='CLIPBOARD_界е\u0301')throw Error('clipboard_roundtrip');checks.native_clipboard_unicode=true;
  const xterm=document.querySelector('.xterm');if(!xterm)throw Error('xterm_missing');
  const separator=document.querySelector('[role="separator"]'),before=separator.getAttribute('aria-valuenow');separator.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));await new Promise(r=>setTimeout(r,100));if(separator.getAttribute('aria-valuenow')===before)throw Error('split_unchanged');checks.split_keyboard=true;
  const settings=[...document.querySelectorAll('nav button')].find(b=>b.textContent==='Настройки');settings.click();await new Promise(r=>setTimeout(r,100));if(!document.querySelector('input[type="password"]'))throw Error('settings_missing');checks.settings_rendered=true;
  if(document.querySelector('.xterm')!==xterm||binding()!=='proof · shell')throw Error('terminal_recreated_on_rerender');checks.terminal_survives_rerender=true;
  const waitUI=async(check,label)=>{for(let i=0;i<150;i++){if(await check())return;await new Promise(r=>setTimeout(r,30));}throw Error(label);};
  await waitUI(()=>document.querySelector('.project-indicator')&&!document.querySelector('.project-indicator-checking'),'project_status_not_loaded');
  if(document.querySelector('.project-indicator-running')||!document.querySelector('.project-indicator').getAttribute('aria-label').includes('proof'))throw Error('project_status_binding');checks.project_status_indicator=true;
  const setInput=(label,value)=>{const input=document.querySelector(`[aria-label="${label}"]`);if(!input)throw Error('missing_'+label);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
  setInput('Модель исполнителя OpenCode','fixture/executor');setInput('Модель контроллера OpenCode','fixture/controller');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();
  await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'model_preview_missing');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(async()=>{const p=(await invoke('projects'))[0];return p.opencode_model==='fixture/executor'&&p.opencode_controller_model==='fixture/controller';},'models_not_saved');
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'model_review_still_open');
  await new Promise(r=>setTimeout(r,100));
  setInput('Модель исполнителя OpenCode','');setInput('Модель контроллера OpenCode','');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'model_clear_preview');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(async()=>{const p=(await invoke('projects'))[0];return p.opencode_model===null&&p.opencode_controller_model===null;},'models_not_cleared');
  checks.project_models_settings=true;
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'model_clear_review_still_open');
  await new Promise(r=>setTimeout(r,150));
  const baseline=(await invoke('projects'))[0];
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'retry_preview_missing');
  let externalReview=await invoke('project_preview',{draft:{...baseline,max_rounds:baseline.max_rounds+1},password:null,token:null});
  await invoke('project_apply',{reviewId:externalReview.review_id});
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>document.querySelector('.settings .error'),'save_error_missing');
  externalReview=await invoke('project_preview',{draft:baseline,password:null,token:null});await invoke('project_apply',{reviewId:externalReview.review_id});
  await waitUI(()=>![...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').disabled,'retry_still_busy');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>!document.querySelector('[aria-label="Просмотр изменений"]'),'retry_not_saved');
  if(document.querySelector('.settings .error'))throw Error('successful_save_retained_old_error');checks.successful_save_clears_error=true;

  await waitUI(()=>document.querySelector('.opencode-keys form'),'provider_keys_missing');
  setInput('Имя переменной провайдера','PROVIDER_API_KEY');setInput('Значение ключа провайдера','fixture-provider-secret');await new Promise(r=>setTimeout(r,50));
  if(document.querySelector('[aria-label="Значение ключа провайдера"]').type!=='password')throw Error('provider_key_not_masked');
  document.querySelector('.opencode-keys form').requestSubmit();
  await waitUI(()=>document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]'),'provider_key_not_saved');
  const keyView=await invoke('opencode_keys_read',{project:'proof'});
  if(keyView.names.join(',')!=='PROVIDER_API_KEY'||JSON.stringify(keyView).includes('fixture-provider-secret')||document.querySelector('[aria-label="Значение ключа провайдера"]').value)throw Error('provider_key_leak');
  await waitUI(()=>document.querySelector('[aria-label="Env-файл исполнителя OpenCode"]').value===keyView.file,'provider_env_not_bound_in_form');
  [...document.querySelectorAll('.opencode-keys button')].find(b=>b.textContent==='Заменить').click();
  setInput('Значение ключа провайдера','fixture-provider-replaced');await new Promise(r=>setTimeout(r,50));
  document.querySelector('.opencode-keys form').requestSubmit();await waitUI(()=>!document.querySelector('[aria-label="Значение ключа провайдера"]').value,'provider_key_not_replaced');
  document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]').click();
  await waitUI(()=>!document.querySelector('[aria-label="Удалить ключ PROVIDER_API_KEY"]'),'provider_key_not_deleted');
  if((await invoke('opencode_keys_read',{project:'proof'})).names.length)throw Error('provider_key_still_present');
  checks.provider_keys_ui=true;checks.provider_keys_redacted=true;

  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Загрузить').click();
  await waitUI(()=>document.querySelector('[aria-label="Содержимое конфигурации OpenCode"]'),'config_editor_missing');
  const editor=document.querySelector('[aria-label="Содержимое конфигурации OpenCode"]');
  const edited='{\n  "$schema": "https://opencode.ai/config.json",\n  "instructions": []\n}\n';
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(editor,edited);editor.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,50));
  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Проверить конфигурацию OpenCode').click();
  await waitUI(()=>document.querySelector('[aria-label="Просмотр конфигурации OpenCode"]'),'config_editor_preview_missing');
  [...document.querySelectorAll('.opencode-editor button')].find(b=>b.textContent==='Сохранить конфигурацию OpenCode').click();
  await waitUI(()=>document.querySelector('.opencode-editor [role="status"]'),'config_editor_save_failed');
  const editedFile=await invoke('opencode_config_read',{project:'proof',file:'opencode.json'});if(editedFile.content!==edited)throw Error('config_editor_bytes');
  checks.opencode_project_editor=true;

  document.querySelector('nav button').click();await new Promise(r=>setTimeout(r,100));
  const bufferText=t=>Array.from({length:t.buffer.active.length},(_,i)=>t.buffer.active.getLine(i).translateToString(true)).join('\n');
  const waitFor=async(check,label)=>{for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,30));}throw Error(label);};
  terminal.input('\x15');terminal.paste("export TAB_MARKER=first; printf 'FIRST_TAB_READY\\n'");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('FIRST_TAB_READY'),'first_tab_ready');
  const firstTab=document.querySelector('[role="tab"][aria-selected="true"]');
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  await waitFor(()=>document.querySelectorAll('.terminal-session').length===2,'second_tab_missing');
  const secondTab=document.querySelector('[role="tab"][aria-selected="true"]');
  const secondTerminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  await waitFor(()=>!secondTab.textContent.includes(' · запуск')&&bufferText(secondTerminal).trim().length>0,'second_tab_not_ready');
  if(secondTerminal===terminal||!terminal.element.closest('[hidden]'))throw Error('first_tab_replaced');
  terminal.paste("printf 'BACKGROUND_TAB_ALIVE\\n'");terminal.input('\r');
  secondTerminal.paste("printf 'SECOND_TAB:%s\\n' ${TAB_MARKER:-independent}");secondTerminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('BACKGROUND_TAB_ALIVE')&&bufferText(secondTerminal).split('\n').includes('SECOND_TAB:independent'),'tab_process_isolation');
  firstTab.click();await new Promise(r=>setTimeout(r,100));
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==terminal)throw Error('tab_buffer_replaced');
  secondTab.parentElement.querySelector('button[aria-label^="Закрыть"]').click();
  await waitFor(()=>document.querySelectorAll('.terminal-session').length===1,'tab_close_missing');
  terminal.paste("printf 'SURVIVING_TAB:%s\\n' $TAB_MARKER");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('SURVIVING_TAB:first'),'closing_tab_killed_peer');
  checks.independent_terminal_tabs=true;checks.background_tab_output=true;checks.tab_close_preserves_peer=true;

  const proofTerminal=terminal,proofTab=document.querySelector('[role="tab"][aria-selected="true"]');
  const otherWorkspace=projects[0].workspace.slice(0,projects[0].workspace.lastIndexOf('/'))+'/other';
  const quote=value=>"'"+value.replaceAll("'","'\\''")+"'";
  terminal.input('\x15');terminal.paste("mkdir -p "+quote(otherWorkspace)+"; printf 'OTHER_WORKSPACE_READY\\n'");terminal.input('\r');
  await waitFor(()=>bufferText(terminal).split('\n').includes('OTHER_WORKSPACE_READY'),'other_workspace_missing');
  [...document.querySelectorAll('nav button')].find(b=>b.textContent==='Настройки').click();
  await waitUI(()=>document.querySelector('.settings'),'other_project_settings');
  [...document.querySelectorAll('.settings button')].find(b=>b.textContent==='Клонировать').click();await new Promise(r=>setTimeout(r,50));
  const editField=(input,value)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
  editField(document.querySelector('.settings input[pattern]'),'other');
  editField(document.querySelector('.settings form .input-action input'),otherWorkspace);await new Promise(r=>setTimeout(r,50));
  document.querySelector('.settings form').requestSubmit();await waitUI(()=>document.querySelector('[aria-label="Просмотр изменений"]'),'other_project_preview');
  [...document.querySelectorAll('[aria-label="Просмотр изменений"] button')].find(b=>b.textContent==='Сохранить').click();
  await waitUI(()=>document.querySelector('.project-select option[value="other"]'),'other_project_not_saved');
  document.querySelector('nav button').click();
  const selectProject=value=>{const select=document.querySelector('.project-select select');select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));};
  proofTerminal.input('\x15');proofTerminal.paste("sleep 1; printf 'PROJECT_BACKGROUND_OUTPUT\\n'");proofTerminal.input('\r');
  selectProject('other');await waitFor(()=>binding()==='Нет сессии','other_showed_proof_terminal');
  if(document.querySelectorAll('.terminal-tabs [role="tab"]').length||document.querySelector('.terminal-session:not([hidden])'))throw Error('foreign_terminal_visible');
  await waitFor(()=>document.querySelector('.dashboard')?.getAttribute('aria-label')==='Задачи проекта other','other_dashboard_binding');
  [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
  await waitFor(()=>binding()==='other · shell','other_terminal_not_opened');
  const otherTerminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
  await waitFor(()=>!document.querySelector('[role="tab"][aria-selected="true"]').textContent.includes(' · запуск')&&bufferText(otherTerminal).includes('$'),'other_pty_not_ready');
  otherTerminal.paste("export TAB_MARKER=other; printf 'OTHER_PROJECT_READY\\n'");otherTerminal.input('\r');
  await waitFor(()=>bufferText(otherTerminal).split('\n').includes('OTHER_PROJECT_READY'),'other_terminal_not_ready');
  const programSelect=document.querySelector('[aria-label="Программа терминала"]');programSelect.value='codex';programSelect.dispatchEvent(new Event('change',{bubbles:true}));
  selectProject('proof');await waitFor(()=>binding()==='proof · shell','proof_active_tab_lost');
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==proofTerminal||document.querySelector('[role="tab"][aria-selected="true"]').id!==proofTab.id)throw Error('project_switch_recreated_terminal');
  if(document.querySelector('[aria-label="Программа терминала"]').value!=='shell'||document.querySelectorAll('.terminal-tabs [role="tab"]').length!==1)throw Error('project_terminal_controls_leaked');
  await waitFor(()=>bufferText(proofTerminal).split('\n').includes('PROJECT_BACKGROUND_OUTPUT'),'hidden_project_output_lost');
  proofTerminal.paste("printf 'PROJECT_SURVIVED:%s\\n' $TAB_MARKER");proofTerminal.input('\r');
  await waitFor(()=>bufferText(proofTerminal).split('\n').includes('PROJECT_SURVIVED:first'),'switching_project_killed_pty');
  closeActive();
  selectProject('other');await waitFor(()=>binding()==='other · shell','closing_proof_killed_other');
  if(document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal!==otherTerminal||document.querySelector('[aria-label="Программа терминала"]').value!=='codex')throw Error('other_project_state_lost');
  otherTerminal.paste("printf 'OTHER_SURVIVED:%s\\n' $TAB_MARKER");otherTerminal.input('\r');
  await waitFor(()=>bufferText(otherTerminal).split('\n').includes('OTHER_SURVIVED:other'),'other_project_process_stopped');
  closeActive();
  selectProject('proof');await waitFor(()=>document.querySelector('.dashboard')?.getAttribute('aria-label')==='Задачи проекта proof','proof_dashboard_not_restored');
  checks.project_workspace_isolation=true;checks.project_switch_preserves_pty=true;checks.project_dashboard_scope=true;
  closeActive();
  const program=document.querySelector('[aria-label="Программа терминала"]');program.value='codex';program.dispatchEvent(new Event('change',{bubbles:true}));
  await waitUI(()=>document.querySelector('[aria-label="Переменные окружения Codex"]')&&!document.querySelector('[aria-label="Переменные окружения Codex"]').disabled,'codex_env_not_loaded');
  document.querySelector('.terminal-launch-env').open=true;
  const envField=document.querySelector('[aria-label="Переменные окружения Codex"]');
  const envText='export AIBRIDGE_TEST_ENV="project value"\n';
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(envField,envText);envField.dispatchEvent(new Event('input',{bubbles:true}));
  await waitUI(()=>!document.querySelector('.terminal-launch-env button').disabled,'codex_env_not_dirty');
  document.querySelector('.terminal-launch-env button').click();
  await waitUI(async()=>await invoke('codex_env_read',{project:'proof'})===envText,'codex_env_not_persisted');
  await waitUI(()=>document.querySelector('.terminal-launch-env .muted').textContent==='Сохранено для проекта','codex_env_status');
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(envField,'');envField.dispatchEvent(new Event('input',{bubbles:true}));
  await waitUI(()=>!document.querySelector('.terminal-launch-env button').disabled,'codex_env_clear_not_dirty');document.querySelector('.terminal-launch-env button').click();
  await waitUI(async()=>await invoke('codex_env_read',{project:'proof'})==='','codex_env_not_cleared');checks.codex_environment_persistence=true;
  const options=await invoke('smoke_options');
  if(options.live_tui){
   for(const profile of ['codex','opencode']){
    const select=document.querySelector('[aria-label="Программа терминала"]');select.value=profile;select.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,50));
    [...document.querySelectorAll('.terminal-pane button')].find(b=>b.textContent==='Открыть').click();
    await new Promise(r=>setTimeout(r,100));
    terminal=document.querySelector('.terminal-session:not([hidden]) .terminal-host').smokeTerminal;
    let ready=false;
    for(let i=0;i<600;i++){
     let text='';for(let row=0;row<terminal.buffer.active.length;row++)text+=terminal.buffer.active.getLine(row).translateToString(true)+'\n';
     if(binding()===`proof · ${profile}`&&new RegExp(profile==='codex'?'codex|OpenAI|trust':'opencode|OpenCode|Trust','i').test(text)){ready=true;break;}
     await new Promise(r=>setTimeout(r,50));
    }
    if(!ready)throw Error(profile+'_tui_missing');
    terminal.input('\x1b[B');terminal.input('\t');
    const size=document.querySelector('[aria-label="Размер шрифта терминала"]');size.value='16';size.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
    if(!document.querySelector('.xterm')||binding()!==`proof · ${profile}`)throw Error(profile+'_tui_resize');
    checks[profile+'_actual_tui_render_input_resize']=true;
    if(profile==='opencode'){
     if(document.querySelectorAll('.terminal-session').length!==2)throw Error('controller_tabs_missing');
     closeActive();await new Promise(r=>setTimeout(r,800));
     if(binding()!=='proof · codex')throw Error('codex_stopped_by_opencode');
     checks.codex_opencode_coexist=true;
     closeActive();await new Promise(r=>setTimeout(r,800));
    }
   }
  }
  await invoke('smoke_complete',{passed:true,checks});
 }catch(error){checks.failure=error.message;await invoke('smoke_complete',{passed:false,checks});}
})();
