import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';

interface Step {id:string;task:string;allowed_paths:string[];test_commands:string[];acceptance_criteria:string[];depends_on?:string[];profile?:string|null}
interface Plan {goal:string;steps:Step[];final_test_commands:string[];delivery:string;max_seconds:number;max_revisions:number;codex_timeout:number;codex_model:string|null}
interface Preview {review_id:string;plan:Plan}
interface Run {run_id:string;status:string;control:string;supervisor_running:boolean;goal:string;delivery:string;phase:string;index:number;steps:{step:Step;phase:string;task_id:string|null;revisions:number;findings?:string|null;review?:{summary?:string;findings?:string[]}}[];remote_result?:{commit:string;reference:string};blocker_code:string|null}
const labels:Record<string,string>={running:'Выполняется',paused:'На паузе',blocked:'Нужен ответ',ready:'Готов к применению',completed:'Завершён',stopped:'Остановлен',failed:'Ошибка',prepare:'Подготовка',submit:'Отправка',active:'Выполнение и проверка',revise:'Доработка',accept:'Принятие',accepted:'Принята',deliver:'Доставка'};
const example=JSON.stringify({version:1,goal:'Описание согласованной цели',steps:[{id:'step-1',task:'Описание задачи',allowed_paths:['src/'],test_commands:['cargo test'],acceptance_criteria:['Проверяемый критерий готовности'],depends_on:[]}],final_test_commands:['cargo test'],delivery:'manual',max_revisions:3},null,2);
function StepView({step}:{step:Step}){return <><p>{step.task}</p><dl><dt>Файлы</dt><dd>{step.allowed_paths.join(', ')}</dd><dt>Проверки</dt><dd>{step.test_commands.join('; ')}</dd><dt>Зависимости</dt><dd>{step.depends_on?.join(', ')||'Нет'}</dd>{step.profile&&<><dt>Профиль</dt><dd>{step.profile}</dd></>}</dl><ul>{step.acceptance_criteria.map((c,i)=><li key={i}>{c}</li>)}</ul></>;}
export function Automation({project}:{project:string}){
 const[draft,setDraft]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState(''),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState('');
 const active=useRef(true),pending=useRef<string|null>(null),operation=useRef(false),generation=useRef(0),draftVersion=useRef(0);
 const cancel=()=>{const id=pending.current;pending.current=null;setPreview(null);if(id)void invoke('automation_cancel',{reviewId:id}).catch(()=>{});};
 const change=(text:string)=>{draftVersion.current++;cancel();setDraft(text);setError('');setNotice('');};
 const refresh=async()=>{if(!project)return;const request=++generation.current;try{const next=await invoke<Run|null>('automation_status',{project});if(active.current&&request===generation.current){setRun(next);setLoaded(true);setReadError('');}}catch(e){if(active.current&&request===generation.current){setReadError(String(e));setLoaded(false);}}};
 useEffect(()=>{active.current=true;let stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{await refresh();if(!stopped)timer=setTimeout(poll,3000);};void poll();return()=>{active.current=false;stopped=true;generation.current++;clearTimeout(timer);if(pending.current)void invoke('automation_cancel',{reviewId:pending.current}).catch(()=>{});};},[project]);
 const check=async()=>{if(operation.current)return;operation.current=true;setBusy(true);setError('');cancel();try{const result=await invoke<Preview>('automation_preview',{project,content:draft});if(active.current){pending.current=result.review_id;setPreview(result);}else void invoke('automation_cancel',{reviewId:result.review_id});}catch(e){if(active.current)setError(String(e));}finally{operation.current=false;if(active.current)setBusy(false);}};
 const start=async()=>{if(!preview||operation.current)return;operation.current=true;setBusy(true);setError('');try{await invoke('automation_start',{project,reviewId:preview.review_id});if(active.current)setNotice('План запущен. Можно продолжить работу или закрыть окно — запуск работает в фоне.');}catch(e){if(active.current)setError(String(e));}finally{pending.current=null;if(active.current){setPreview(null);await refresh();setBusy(false);}operation.current=false;}};
 const control=async(action:string)=>{if(!run||operation.current)return;operation.current=true;setBusy(true);setError('');try{await invoke('automation_control',{project,run:run.run_id,action});if(active.current)setNotice(action==='pause'?'Пауза запрошена. Текущая операция завершится перед остановкой.':action==='stop'?'Остановка запрошена. Дождитесь завершения очистки.':'Выполнение продолжено.');}catch(e){if(active.current)setError(String(e));}finally{if(active.current){await refresh();setBusy(false);}operation.current=false;}};
 const upload=async(file:File|undefined)=>{if(!file)return;const version=draftVersion.current;if(file.size>1_000_000){setError('План превышает 1 МБ');return;}try{const text=await file.text();if(active.current&&version===draftVersion.current)change(text);}catch{if(active.current)setError('Не удалось прочитать файл плана');}};
 if(!project)return <p className="empty">Выберите проект для автоматизации.</p>;
 const unfinished=run&&!['ready','completed','stopped'].includes(run.status);
 const stopping=run?.control==='stop';
 const canResume=unfinished&&!stopping&&!run.supervisor_running;
 return <section className="automation" aria-label="Автоматизация проекта"><div className="pane-bar"><h2>Автоматизация</h2><button disabled={busy} onClick={()=>void refresh()}>Обновить статус</button></div>
 <p>Обсудите задачи в «Codex через мост» и попросите оформить согласованный план в JSON. Загрузите файл или вставьте план ниже, проверьте его и утвердите запуск.</p>
 {readError&&<p role="alert" className="error">{readError}</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {run&&<section className="automation-run" aria-label="Текущий запуск"><div className="pane-bar"><h3>{labels[run.status]??run.status}</h3><span>{run.supervisor_running?'Координатор работает':'Координатор остановлен'}</span></div><p>{run.goal}</p><p className="muted">Запуск {run.run_id}</p>
 <progress aria-label="Выполненные задачи" value={run.steps.filter(s=>s.phase==='accepted').length} max={run.steps.length}/><span> {run.steps.filter(s=>s.phase==='accepted').length} / {run.steps.length} (включая итоговую проверку)</span>
 {run.blocker_code&&<p role="alert">Причина остановки: {run.blocker_code}. Устраните причину и продолжите запуск.</p>}
 <div className="automation-actions"><button disabled={busy||!unfinished||!!stopping||run.control==='pause'||run.status==='paused'||!run.supervisor_running} onClick={()=>void control('pause')}>Пауза</button><button disabled={busy||!canResume} onClick={()=>void control('resume')}>Продолжить</button><button disabled={busy||!unfinished} onClick={()=>void control('stop')}>{stopping?'Повторить остановку':'Остановить'}</button></div>
 <ol>{run.steps.map((item,i)=><li key={item.step.id} aria-current={i===run.index?'step':undefined}><details open={i===run.index}><summary>{item.step.id==='__final__'?'Итоговая проверка':item.step.id} · {labels[item.phase]??item.phase} · доработок: {item.revisions}</summary><StepView step={item.step}/>{item.task_id&&<p className="muted">Задача: {item.task_id} — подробности доступны в Dashboard.</p>}{item.findings&&<p>Замечания для доработки: {item.findings}</p>}{item.review?.summary&&<p>Ревью: {item.review.summary}</p>}{!!item.review?.findings?.length&&<ul>{item.review.findings.map((f,j)=><li key={j}>{f}</li>)}</ul>}</details></li>)}</ol>
 {run.remote_result?.commit&&<p>Git-снимок результата: <code>{run.remote_result.commit}</code><br/>Ветка: <code>{run.remote_result.reference}</code></p>}
 {run.status==='ready'&&<p>Итог проверен и подготовлен для отдельной доставки.</p>}
 </section>}
 <section aria-label="Новый план"><h3>Новый план</h3>{unfinished&&<p>Новый запуск доступен после завершения или остановки текущего.</p>}<div className="automation-actions"><label className="plan-file">Загрузить JSON<input aria-label="Файл плана" type="file" accept=".json,application/json" disabled={busy||!!unfinished} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><button disabled={busy||!!unfinished} onClick={()=>change(example)}>Пример плана</button></div>
 <textarea aria-label="JSON-план автоматизации" spellCheck={false} disabled={busy||!!unfinished} value={draft} placeholder={example} onChange={e=>change(e.target.value)}/><button disabled={busy||!draft.trim()||!!unfinished||!loaded} onClick={()=>void check()}>{busy?'Обработка…':'Проверить план'}</button>
 {preview&&<section className="review" aria-label="Согласование плана"><h3>{preview.plan.goal}</h3><ol>{preview.plan.steps.map(step=><li key={step.id}><h4>{step.id}</h4><StepView step={step}/></li>)}</ol><dl><dt>Итоговые проверки</dt><dd>{preview.plan.final_test_commands.join('; ')}</dd><dt>Доставка</dt><dd>{preview.plan.delivery==='apply'?'Автоматически применить итог в основной каталог':'Подготовить итог для ручного применения'}</dd><dt>Лимит времени</dt><dd>{preview.plan.max_seconds} секунд</dd><dt>Лимит доработок</dt><dd>{preview.plan.max_revisions} на задачу</dd><dt>Таймаут Codex</dt><dd>{preview.plan.codex_timeout} секунд</dd><dt>Модель Codex</dt><dd>{preview.plan.codex_model||'По умолчанию'}</dd></dl><p>Запуск выполняет задачи, проверки, ревью и доработки автоматически. Требуется чистый Git-репозиторий и отсутствие незавершённых задач.</p><button className="primary" disabled={busy||!!unfinished||!loaded} onClick={()=>void start()}>Утвердить и запустить</button><button disabled={busy} onClick={cancel}>Отменить</button></section>}
 </section></section>;
}
