import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {statuses,type Snapshot,type Task} from './types';
import {TaskStatusEditor} from './TaskStatusEditor';
export function Dashboard({project,onAttach}:{project:string;onAttach:(task:Task)=>void}){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[active,setActive]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState(''),[offset,setOffset]=useState(0),[scroll,setScroll]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[paused,setPaused]=useState(false);const[recovering,setRecovering]=useState(false),[recoveryMessage,setRecoveryMessage]=useState(''),[refreshRevision,setRefreshRevision]=useState(0);const linked=false,scroller=useRef<HTMLDivElement>(null),currentSelection=useRef(selected);currentSelection.current=selected;
 useEffect(()=>{setOffset(0);setSelected('');setSnapshot(null);},[project]);
 useEffect(()=>{setScroll(0);if(scroller.current)scroller.current.scrollTop=0;},[project,active,linked,offset,search,status]);
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;let revision="",lastFull=0;const refresh=async()=>{if(!project){setLoading(false);return;}try{const stamp=await invoke<string>('dashboard_revision',{project,linked});if(stamp===revision&&Date.now()-lastFull<30000)return;const next=await invoke<Snapshot>('dashboard',{query:{project,active_only:active,linked,offset,limit:100,search,status:status||null}});if(!stopped){setSnapshot(next);setError('');revision=stamp;lastFull=Date.now();}}catch(e){if(!stopped)setError(String(e));}finally{if(!stopped){setLoading(false);if(!paused)timer=setTimeout(refresh,2000);}}};setLoading(!snapshot);void refresh();return()=>{stopped=true;clearTimeout(timer);};},[project,active,linked,offset,paused,search,status,refreshRevision]);
 const tasks=snapshot?.tasks??[];const detail=tasks.find(t=>t.task_id===selected)??snapshot?.tasks.find(t=>t.task_id===selected);const start=Math.max(0,Math.floor(scroll/72)-4);const visible=tasks.slice(start,start+18);
 const recover=async(task:Task)=>{setRecovering(true);setRecoveryMessage('');try{await invoke('task_recover',{project:task.project_id,task:task.task_id});if(currentSelection.current===task.task_id)setRecoveryMessage('Мост проверяет продолжение сессии: результат появится после verifier и сбора изменений.');setPaused(false);}catch(e){if(currentSelection.current===task.task_id)setRecoveryMessage(String(e));}finally{setRecovering(false);setRefreshRevision(r=>r+1);}};
 useEffect(()=>{setRecoveryMessage('');},[selected]);
 return <section className="dashboard" aria-label={`Задачи проекта ${project}`}><div className="pane-bar"><h2>Задачи</h2><span className="pill">Активных: {snapshot?.active_count??0}</span><span className="pill">Writers: {snapshot?.writer_count??0}</span><span className="pill">Ожидают: {snapshot?.waiting_count??0}</span><button aria-pressed={paused} title={paused?'Возобновить автоматическое обновление задач':'Приостановить автоматическое обновление задач'} onClick={()=>setPaused(p=>!p)}>{paused?'Возобновить обновления':'Пауза обновлений'}</button></div>{paused&&<p className="dashboard-paused" role="status">Автообновление приостановлено — статусы задач могут устареть. Нажмите «Возобновить обновления».</p>}<div className="filters"><label className="check"><input type="checkbox" checked={active} onChange={e=>{setActive(e.target.checked);setOffset(0);}}/>Только активные</label><input aria-label="Поиск задач" placeholder="Поиск задач…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);setScroll(0);if(scroller.current)scroller.current.scrollTop=0;}}/><select aria-label="Фильтр статуса" value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);setScroll(0);if(scroller.current)scroller.current.scrollTop=0;}}><option value="">Все статусы</option>{Object.entries(statuses).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></div>
 {error&&<p role="alert" className="error">{error}</p>}{snapshot?.errors.map((e,i)=><p className="error" key={i}>{JSON.stringify(e)}</p>)}{loading?<p className="empty">Загрузка…</p>:!tasks.length?<p className="empty">{project?'Задач пока нет':'Выберите проект'}</p>:<div className="task-list" ref={scroller} onScroll={e=>setScroll(e.currentTarget.scrollTop)} role="list" aria-label="Задачи"><div style={{height:tasks.length*72,position:'relative'}}>{visible.map((t,i)=><button key={t.task_id} className={`task-row ${selected===t.task_id?'selected':''}`} style={{position:'absolute',top:(start+i)*72,left:0,right:0,height:68}} onClick={()=>setSelected(t.task_id)} role="listitem"><span><strong>{t.title}</strong><small>{t.project_id} · {t.task_id.slice(0,8)} · {new Date(t.updated_at).toLocaleString()}</small></span><span className={`status status-${t.status}`}>{statuses[t.status]??t.status}</span></button>)}</div></div>}
 <div className="pagination"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Назад</button><span>{snapshot?.total?offset+1:0}–{offset+(snapshot?.tasks.length??0)} / {snapshot?.total??0}</span><button disabled={offset+100>=(snapshot?.total??0)} onClick={()=>setOffset(offset+100)}>Далее</button></div>
 {detail&&<article className="detail"><div className="pane-bar"><h3>{statuses[detail.status]??detail.status}</h3><TaskStatusEditor key={detail.task_id} task={detail} onUpdated={()=>setRefreshRevision(r=>r+1)}/><button disabled={['accepted','closed'].includes(detail.status)||(detail.status==='failed'&&!detail.recoverable)} onClick={()=>onAttach(detail)}>Открыть сессию</button>{detail.recoverable&&<button disabled={recovering} onClick={()=>void recover(detail)}>{recovering?'Запуск проверки…':'Проверить продолжение сессии'}</button>}</div>{detail.recoverable&&<p>После ручного продолжения OpenCode запустите проверку: мост прочитает ту же сессию и выполнит свои проверки без повторной отправки задания.</p>}{recoveryMessage&&<p role="status">{recoveryMessage}</p>}<p>{detail.title}</p><dl><dt>Проект / задача</dt><dd>{detail.project_id} / {detail.task_id}</dd><dt>Режим</dt><dd>{detail.execution_mode}</dd><dt>Доставка</dt><dd>{detail.delivery_state??'Не доставлена'} · {detail.delivery_mode}</dd><dt>Последний отказ доставки</dt><dd>{detail.delivery_refusal?`${detail.delivery_refusal.code} · ${detail.delivery_refusal.created_at}`:"—"}</dd><dt>Workflow</dt><dd>{detail.workflow_id??'—'}</dd></dl><details><summary>Репозитории и проверки</summary><pre>{JSON.stringify({base_head:detail.base_head,allowed_paths:detail.allowed_paths,test_commands:detail.test_commands,repositories:detail.repositories},null,2)}</pre></details><details open><summary>Зависимости workflow</summary><div className="workflow-graph" role="list" aria-label="Граф зависимостей">{(Array.isArray(detail.depends_on)?detail.depends_on:[]).map((id:string)=><div role="listitem" key={id}><code>{id}</code><span aria-label="зависит от"> → </span><strong>{detail.task_id.slice(0,8)}</strong><small> · {statuses[tasks.find(t=>t.task_id===id)?.status??'']??'Вне текущей страницы'}</small></div>)}{(!Array.isArray(detail.depends_on)||!detail.depends_on.length)&&<p>Корневая задача без зависимостей</p>}</div></details><details open><summary>Usage и бюджет</summary><pre>{JSON.stringify({usage:detail.usage,budget:detail.budget},null,2)}</pre></details>{detail.rounds.map(r=><details key={r.number} open={r===detail.rounds[0]}><summary>Раунд {r.number} · {r.status} · {String(r.verification?.status??'без проверки')}</summary><h4>Verifier</h4><pre>{JSON.stringify(r.verification,null,2)}</pre><h4>Findings</h4><pre>{JSON.stringify(r.findings,null,2)}</pre><h4>Checkpoint</h4><pre>{JSON.stringify(r.checkpoint,null,2)}</pre></details>)}</article>}
 {!!snapshot?.reservations.length&&<details><summary>Резервации writers ({snapshot.reservations.length})</summary><pre>{JSON.stringify(snapshot.reservations,null,2)}</pre></details>}
 {!!snapshot?.runs.length&&<section className="runs"><h3>Автоматические запуски</h3>{snapshot.runs.map((r,i)=><article key={i}><strong>{{ready:'Готов к доставке',completed:'Завершён',running:'Выполняется',blocked:'Заблокирован',stopped:'Остановлен'}[String(r.status)]??String(r.status)} · {String(r.control)}</strong><pre>{JSON.stringify(r,null,2)}</pre></article>)}</section>}
 </section>;
}
