import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {open} from '@tauri-apps/plugin-dialog';
import type {Project,Review} from './types';
const empty:Project={id:'',workspace:'',opencode_url:'http://127.0.0.1:4101',mcp_url:'http://127.0.0.1:4201/mcp',max_rounds:3,execution_mode:'direct',delivery_mode:'manual',max_active_tasks:1,allow_parallel_writers:false,auto_approve_state_directory:false,auto_approve_permissions:[],auto_approve_external_directories:[]};
export function Settings({project,projects,onSaved}:{project:Project|undefined;projects:Project[];onSaved:()=>void}){
 const[draft,setDraft]=useState<Project>(project??empty),[creating,setCreating]=useState(!project),[password,setPassword]=useState(''),[token,setToken]=useState(''),[review,setReview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setDraft(project??empty);setCreating(!project);setReview(null);setPassword('');setToken('');},[project]);
 const field=<K extends keyof Project>(key:K,value:Project[K])=>{setDraft(d=>({...d,[key]:value}));setReview(null);};
 const preview=async()=>{setBusy(true);setError('');try{const r=await invoke<Review>('project_preview',{draft,password:password||null,token:token||null});setReview(r);setPassword('');setToken('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async()=>{if(!review)return;setBusy(true);try{await invoke('project_apply',{reviewId:review.review_id});setReview(null);onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const create=(clone:boolean)=>{setCreating(true);setReview(null);setDraft({...((clone&&project)?project:empty),id:'',mcp_url:'http://127.0.0.1:4201/mcp',opencode_url:'http://127.0.0.1:4101'});};
 return <section className="settings"><div className="pane-bar"><h2>Настройки проекта</h2><button onClick={()=>create(false)}>Новый</button><button disabled={!project} onClick={()=>create(true)}>Клонировать</button></div><p className="muted">Перед сохранением завершите активные задачи и остановите сервисы. Изменения сначала показываются для проверки.</p>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void preview();}}><div className="form-grid">
 <label>ID<input required disabled={!creating} pattern="[a-z0-9][a-z0-9_-]{0,63}" value={draft.id} onChange={e=>field('id',e.target.value)}/></label>
 <label className="wide">Workspace<div className="input-action"><input required value={draft.workspace} onChange={e=>field('workspace',e.target.value)}/><button type="button" onClick={()=>void open({directory:true,multiple:false}).then(path=>{if(typeof path==='string')field('workspace',path);}).catch(e=>setError(String(e)))}>Выбрать…</button></div></label>
 <label>OpenCode endpoint<input required value={draft.opencode_url} onChange={e=>field('opencode_url',e.target.value)}/></label><label>MCP endpoint<input value={draft.mcp_url??''} onChange={e=>field('mcp_url',e.target.value||null)}/></label>
 <label>Режим исполнения<select value={draft.execution_mode} onChange={e=>field('execution_mode',e.target.value)}><option value="direct">Основной workspace</option><option value="worktree">Отдельный worktree</option></select></label><label>Доставка<select value={draft.delivery_mode} onChange={e=>field('delivery_mode',e.target.value)}><option value="manual">Вручную</option><option value="on_accept">При принятии</option></select></label>
 <label>Максимум раундов<input type="number" min={1} required value={draft.max_rounds} onChange={e=>field('max_rounds',Number(e.target.value))}/></label><label>Максимум активных задач<input type="number" min={1} required value={draft.max_active_tasks} onChange={e=>field('max_active_tasks',Number(e.target.value))}/></label>
 <label className="check"><input type="checkbox" checked={draft.allow_parallel_writers} onChange={e=>field('allow_parallel_writers',e.target.checked)}/>Параллельные writers</label><label className="check"><input type="checkbox" checked={draft.auto_approve_state_directory} onChange={e=>field('auto_approve_state_directory',e.target.checked)}/>Доступ исполнителя к Rust state</label>
 <label>Разрешения (по одному в строке)<textarea value={draft.auto_approve_permissions.join('\n')} onChange={e=>field('auto_approve_permissions',e.target.value.split('\n').filter(Boolean))}/></label><label>Доверенные каталоги<textarea value={draft.auto_approve_external_directories.join('\n')} onChange={e=>field('auto_approve_external_directories',e.target.value.split('\n').filter(Boolean))}/></label>
 <label>Новый пароль OpenCode<input type="password" autoComplete="new-password" value={password} placeholder="Оставить текущий" onChange={e=>setPassword(e.target.value)}/></label><label>Новый MCP token<input type="password" autoComplete="new-password" value={token} placeholder="Оставить текущий" onChange={e=>setToken(e.target.value)}/></label></div><button className="primary" disabled={busy}>Проверить изменения</button></form>
 <p className="muted">Настроено проектов: {projects.length}. Значения credentials не загружаются в интерфейс.</p>
 {review&&<div className="review" role="dialog" aria-label="Просмотр изменений"><h3>Изменения перед сохранением</h3><div className="diff-columns"><div><h4>Сейчас</h4><pre>{JSON.stringify(review.before,null,2)}</pre></div><div><h4>После сохранения</h4><pre>{JSON.stringify(review.after,null,2)}</pre></div></div>{review.credentials_changed&&<p>Credentials будут обновлены.</p>}<button className="primary" disabled={busy} onClick={()=>void save()}>Сохранить</button><button onClick={()=>{invoke('project_cancel',{reviewId:review.review_id}).catch(()=>{});setReview(null);}}>Отмена</button></div>}
 </section>;
}
