import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {open} from '@tauri-apps/plugin-dialog';
import type {Project,Review} from './types';
import {FieldHelp} from './FieldHelp';
import {PermissionChoices} from './PermissionChoices';
import {OpenCodeConfigEditor} from './OpenCodeConfigEditor';
import {OpenCodeKeys} from './OpenCodeKeys';
import {ProjectRemoval} from './ProjectRemoval';
import {RemoteSettings} from './RemoteSettings';
const empty:Project={id:'',workspace:'',opencode_url:'',mcp_url:null,opencode_model:null,opencode_controller_model:null,opencode_env_file:null,max_rounds:3,execution_mode:'direct',delivery_mode:'manual',max_active_tasks:1,allow_parallel_writers:false,auto_approve_state_directory:false,auto_approve_permissions:[],auto_approve_external_directories:[]};
export function Settings({project,projects,onSaved}:{project:Project|undefined;projects:Project[];onSaved:()=>void}){
 const[draft,setDraft]=useState<Project>(project??empty),[creating,setCreating]=useState(!project),[password,setPassword]=useState(''),[token,setToken]=useState(''),[review,setReview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[portsBusy,setPortsBusy]=useState(!project);
 const portRequest=useRef(0);
 const suggestEndpoints=async()=>{
  const request=++portRequest.current;
  setPortsBusy(true);
  try{
   const endpoints=await invoke<{opencode_url:string;mcp_url:string}>('project_suggest_endpoints');
   if(request===portRequest.current)setDraft(d=>({...d,...endpoints}));
  }catch(e){if(request===portRequest.current)setError(String(e));}
  finally{if(request===portRequest.current)setPortsBusy(false);}
 };
 useEffect(()=>{
  ++portRequest.current;
  setDraft(project??empty);setCreating(!project);setReview(null);setPassword('');setToken('');setError('');setPortsBusy(false);
  if(!project)void suggestEndpoints();
  return()=>{++portRequest.current;};
 },[project]);
 const field=<K extends keyof Project>(key:K,value:Project[K])=>{setDraft(d=>({...d,[key]:value}));setReview(null);};
 const [choosingDirectories,setChoosingDirectories]=useState(false);
 const chooseDirectories=async()=>{
  setChoosingDirectories(true);
  try {
   const paths=await open({directory:true,multiple:true,title:'Добавить доверенные каталоги'});
   if(paths){
    const selected=typeof paths==='string'?[paths]:paths;
    setDraft(d=>d.id===draft.id&&d.workspace===draft.workspace?{...d,auto_approve_external_directories:[...new Set([...d.auto_approve_external_directories,...selected])]}:d);
    setReview(null);
   }
  } catch(e){setError(String(e));}
  finally{setChoosingDirectories(false);}
 };
 const preview=async()=>{setBusy(true);setError('');try{const r=await invoke<Review>('project_preview',{draft,password:password||null,token:token||null});setReview(r);setPassword('');setToken('');}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async()=>{if(!review)return;setBusy(true);setError('');try{await invoke('project_apply',{reviewId:review.review_id});setReview(null);onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const create=(clone:boolean)=>{setError('');setCreating(true);setReview(null);setPassword('');setToken('');setDraft({...((clone&&project)?project:empty),id:'',mcp_url:null,opencode_url:''});void suggestEndpoints();};
 return <section className="settings"><div className="pane-bar"><h2>Настройки проекта</h2><button disabled={busy||portsBusy} onClick={()=>create(false)}>Новый</button><button disabled={!project||busy||portsBusy} onClick={()=>create(true)}>Клонировать</button></div> {!creating&&project&&<ProjectRemoval key={project.id} project={project.id} disabled={busy||!!review} onDeleted={onSaved}/> }<p className="muted">Изменения сначала показываются для проверки. Перед сохранением проверяется активность изменяемого проекта и зависимых от него проектов.</p>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void preview();}}><div className="form-grid">
 <label><FieldHelp label="ID" description="Уникальное имя проекта: 1–64 символа, маленькие латинские буквы, цифры, дефис и подчёркивание. Первый символ — буква или цифра. После создания ID не меняется."/><input required disabled={!creating} pattern="[a-z0-9][a-z0-9_-]{0,63}" value={draft.id} onChange={e=>field('id',e.target.value)}/></label>
 <label className="wide"><FieldHelp label="Workspace" description="Существующий каталог Git-проекта. В основном режиме агент меняет файлы здесь; в режиме worktree задача выполняется в отдельном checkout."/><div className="input-action"><input required value={draft.workspace} onChange={e=>field('workspace',e.target.value)}/><button type="button" onClick={()=>void open({directory:true,multiple:false}).then(path=>{if(typeof path==='string')field('workspace',path);}).catch(e=>setError(String(e)))}>Выбрать…</button></div></label>
 <RemoteSettings value={draft.remote_execution??null} onChange={value=>field('remote_execution',value)} project={draft.id}/>
 <label><FieldHelp label="OpenCode endpoint" description="Адрес локального сервиса OpenCode, которому AIbridge отправляет задачи. Start запускает сервис. Например http://127.0.0.1:4101. Для каждого проекта нужен отдельный свободный порт."/><input required disabled={portsBusy} placeholder={portsBusy?'Подбор свободного порта…':''} value={draft.opencode_url} onChange={e=>field('opencode_url',e.target.value)}/></label><label><FieldHelp label="MCP endpoint" description="Адрес MCP-сервера AIbridge для управления задачами из Codex/OpenCode. Нужен для Start. Например http://127.0.0.1:4201/mcp. Для каждого проекта нужен отдельный свободный порт."/><input disabled={portsBusy} placeholder={portsBusy?'Подбор свободного порта…':''} value={draft.mcp_url??''} onChange={e=>field('mcp_url',e.target.value||null)}/></label>
 <label><FieldHelp label="Модель исполнителя OpenCode" description="Модель для выполнения задач в формате provider/model. Пустое поле использует настройки OpenCode. Собственная модель профиля задачи имеет приоритет. Изменение применяется к новым задачам."/><input aria-label="Модель исполнителя OpenCode" placeholder="По умолчанию (provider/model)" value={draft.opencode_model??''} onChange={e=>field('opencode_model',e.target.value||null)}/></label>
 <label><FieldHelp label="Модель контроллера OpenCode" description="Отдельная модель интерактивного контроллера bridge-controller в формате provider/model. Пустое поле использует настройки OpenCode. Не меняет модель исполнителя или Codex. Применяется при новом запуске контроллера."/><input aria-label="Модель контроллера OpenCode" placeholder="По умолчанию (provider/model)" value={draft.opencode_controller_model??''} onChange={e=>field('opencode_controller_model',e.target.value||null)}/></label>
 <label className="wide"><FieldHelp label="Env-файл исполнителя OpenCode" description="Файл переменных NAME=value для сервисов и исполнителя OpenCode. Можно выбрать файл или ввести путь: относительный путь считается от каталога projects.toml. Файл должен существовать, принадлежать вам и иметь права 0600. Ключи можно добавить ниже в разделе «Ключи провайдеров OpenCode» — приложение создаст файл само. Существующие значения в UI не загружаются. Для применения перезапустите сервисы."/><div className="input-action"><input aria-label="Env-файл исполнителя OpenCode" placeholder="Не задан" value={draft.opencode_env_file??''} onChange={e=>field('opencode_env_file',e.target.value||null)}/><button type="button" onClick={()=>void open({directory:false,multiple:false,title:'Env-файл OpenCode'}).then(path=>{if(typeof path==='string')field('opencode_env_file',path);}).catch(e=>setError(String(e)))}>Выбрать файл…</button></div></label>
 <label><FieldHelp label="Режим исполнения" description="Основной workspace: изменения сразу в каталоге проекта. Отдельный worktree: задача выполняется в отдельном Git checkout, а результат переносится в основной каталог отдельной доставкой."/><select value={draft.execution_mode} onChange={e=>field('execution_mode',e.target.value)}><option value="direct">Основной workspace</option><option value="worktree">Отдельный worktree</option></select></label><label><FieldHelp label="Доставка" description="Вручную: принятие задачи не переносит результат из worktree, нужна отдельная команда доставки. При принятии: после принятия AIbridge пытается перенести результат автоматически; доступно только для worktree. Commit и push не выполняются."/><select value={draft.delivery_mode} onChange={e=>field('delivery_mode',e.target.value)}><option value="manual">Вручную</option><option value="on_accept">При принятии</option></select></label>
 <label><FieldHelp label="Максимум раундов" description="Лимит попыток выполнения одной задачи, включая исправления после review. Например 3 — первая попытка и до двух раундов исправлений. Положительное целое число."/><input type="number" min={1} required value={draft.max_rounds} onChange={e=>field('max_rounds',Number(e.target.value))}/></label><label><FieldHelp label="Максимум активных задач" description="Лимит одновременно активных задач проекта. По умолчанию 1. Увеличение лимита само по себе не разрешает параллельное изменение файлов."/><input type="number" min={1} required value={draft.max_active_tasks} onChange={e=>field('max_active_tasks',Number(e.target.value))}/></label>
 <label className="check"><input type="checkbox" checked={draft.allow_parallel_writers} onChange={e=>field('allow_parallel_writers',e.target.checked)}/><FieldHelp label="Параллельные writers" description="Разрешает нескольким исполнителям одновременно менять файлы в отдельных worktree при непересекающихся разрешённых областях. Доступно только в режиме worktree. Для первого запуска можно выключить."/></label><label className="check"><input type="checkbox" checked={draft.auto_approve_state_directory} onChange={e=>field('auto_approve_state_directory',e.target.checked)}/><FieldHelp label="Доступ исполнителя к Rust state" description="Автоматически одобрять запросы OpenCode на доступ к служебному каталогу Rust state. Для первого запуска можно оставить выключенным."/></label>
 <PermissionChoices value={draft.auto_approve_permissions} onChange={value=>field('auto_approve_permissions',value)}/><div className="trusted-directories"><FieldHelp label="Доверенные каталоги" description="Существующие внешние каталоги, доступ к которым можно автоматически одобрять. Добавьте папки через кнопку выбора или введите абсолютные пути вручную, по одному в строке. Корень / запрещён. Если внешние каталоги не нужны, оставьте пустым."/><textarea aria-label="Доверенные каталоги" value={draft.auto_approve_external_directories.join('\n')} onChange={e=>field('auto_approve_external_directories',e.target.value.split('\n').filter(Boolean))}/><button type="button" disabled={busy||choosingDirectories} onClick={()=>void chooseDirectories()}>{choosingDirectories?'Выбор…':'Добавить каталоги…'}</button></div>
 <label><FieldHelp label="Новый пароль OpenCode" description="Пароль локального сервиса OpenCode, а не API-ключ модели. Для нового проекта пустое поле позволяет автоматически создать пароль при запуске проекта; для существующего сохраняет текущий. Файл credentials назначается автоматически."/><input type="password" autoComplete="new-password" value={password} placeholder="Оставить текущий" onChange={e=>setPassword(e.target.value)}/></label><label><FieldHelp label="Новый MCP token" description="Токен доступа к MCP-серверу AIbridge, а не токен Codex или провайдера. Для нового проекта пустое поле позволяет автоматически создать токен при запуске проекта; для существующего сохраняет текущий. Файл credentials назначается автоматически."/><input type="password" autoComplete="new-password" value={token} placeholder="Оставить текущий" onChange={e=>setToken(e.target.value)}/></label></div><button className="primary" disabled={busy||portsBusy}>Проверить изменения</button></form>
 {!creating&&project&&!draft.remote_execution&&<OpenCodeKeys key={project.id+' '+(project.opencode_env_file??'')} project={project.id} onConfigured={file=>field('opencode_env_file',file)}/> }
 {!creating&&project&&!draft.remote_execution?<OpenCodeConfigEditor key={project.id+' '+project.workspace} project={project.id} workspace={project.workspace}/>:<p className="muted">{draft.remote_execution?'Настройте модели, ключи и opencode.json на втором ПК.':'После сохранения проекта здесь можно открыть и настроить его opencode.json или opencode.jsonc.'}</p>}
 <p className="muted">Настроено проектов: {projects.length}. Значения credentials не загружаются в интерфейс.</p>
 {review&&<div className="review" role="dialog" aria-label="Просмотр изменений"><h3>Изменения перед сохранением</h3><div className="diff-columns"><div><h4>Сейчас</h4><pre>{JSON.stringify(review.before,null,2)}</pre></div><div><h4>После сохранения</h4><pre>{JSON.stringify(review.after,null,2)}</pre></div></div>{review.credentials_changed&&<p>Credentials будут обновлены.</p>}<button className="primary" disabled={busy} onClick={()=>void save()}>Сохранить</button><button onClick={()=>{invoke('project_cancel',{reviewId:review.review_id}).catch(()=>{});setReview(null);}}>Отмена</button></div>}
 </section>;
}
