import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Terminal} from '@xterm/xterm';
import {FitAddon} from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import type {TerminalEvent} from './types';
export function TerminalPane({project,attach}:{project:string;attach:{task:string;project:string;nonce:number}|null}){
 const host=useRef<HTMLDivElement>(null),term=useRef<Terminal|null>(null),fit=useRef<FitAddon|null>(null),session=useRef<string|null>(null),openGeneration=useRef(0);
 const[profile,setProfile]=useState('shell'),[binding,setBinding]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fontSize,setFontSize]=useState(()=>Number(localStorage.getItem('aibridge-terminal-font'))||14);
 useEffect(()=>{const t=new Terminal({fontSize:14,fontFamily:'"DejaVu Sans Mono",monospace',scrollback:5000,theme:{background:'#10151c',foreground:'#d5dfed',cursor:'#70d9ae'},cursorBlink:true});const f=new FitAddon();t.loadAddon(f);t.open(host.current!);term.current=t;fit.current=f;f.fit();
  const data=t.onData(data=>{if(session.current)invoke('terminal_write',{session:session.current,bytes:Array.from(new TextEncoder().encode(data))}).catch(e=>setError(String(e)));});
  const resize=new ResizeObserver(()=>{f.fit();if(session.current)invoke('terminal_resize',{session:session.current,rows:t.rows,cols:t.cols}).catch(e=>setError(String(e)));});resize.observe(host.current!);
  let stopped=false;const poll=async()=>{if(stopped)return;try{const id=session.current;if(id){const events=await invoke<TerminalEvent[]>('terminal_read',{session:id});if(session.current===id)for(const e of events){if(e.type==='data')await new Promise<void>(resolve=>t.write(new Uint8Array(e.bytes),resolve));else if(e.type==='exit'){t.writeln(`\r\n[процесс завершён: ${e.code}]`);session.current=null;setBinding(b=>b+' · завершена');invoke('terminal_close',{session:id}).catch(()=>{});}else setError(e.message);}}}catch(e){setError(String(e));}if(!stopped)setTimeout(poll,32);};poll();
  return()=>{stopped=true;openGeneration.current++;const id=session.current;session.current=null;setBinding('');if(id)invoke('terminal_close',{session:id}).catch(()=>{});resize.disconnect();data.dispose();t.dispose();term.current=null;};
 },[]);
 useEffect(()=>{if(term.current){term.current.options.fontSize=fontSize;fit.current?.fit();}localStorage.setItem('aibridge-terminal-font',String(fontSize));},[fontSize]);
 const connect=async(target=project,selected=profile,task:string|null=null)=>{const generation=++openGeneration.current;setBusy(true);setError('');try{if(session.current){const id=session.current;session.current=null;await invoke('terminal_close',{session:id});}const t=term.current;if(!t)return;t.reset();fit.current?.fit();const id=await invoke<string>('terminal_open',{project:target,profile:selected,task,rows:t.rows,cols:t.cols});if(generation!==openGeneration.current){await invoke('terminal_close',{session:id});return;}session.current=id;setBinding(`${target} · ${selected}${task?' · '+task.slice(0,8):''}`);t.focus();}catch(e){setError(String(e));}finally{setBusy(false);}};
 useEffect(()=>{if(attach)void connect(attach.project,'attach',attach.task);},[attach]);
 return <section className="terminal-pane"><div className="pane-bar"><strong>Терминал</strong><span className="muted">{binding||'Нет сессии'}</span><select aria-label="Программа терминала" value={profile} onChange={e=>setProfile(e.target.value)}><option value="shell">Shell</option><option value="opencode">OpenCode</option><option value="codex">Codex</option></select><select aria-label="Размер шрифта терминала" value={fontSize} onChange={e=>setFontSize(Number(e.target.value))}>{[12,14,16,18,20].map(size=><option key={size} value={size}>{size}px</option>)}</select><button disabled={!project||busy} onClick={()=>void connect()}>{busy?'Запуск…':'Открыть'}</button><button disabled={!session.current||busy} onClick={()=>{const id=session.current;session.current=null;setBinding('');if(id)invoke('terminal_close',{session:id}).catch(e=>setError(String(e)));}}>Завершить</button></div>{error&&<p role="alert" className="error">{error}</p>}<div className="terminal-host" ref={host}/></section>;
}
