export interface RemoteExecution {host:string;user:string;port:number;executable:string;config:string;state_root:string;project:string;repository:string}
export interface Project {id:string;workspace:string;remote_execution?:RemoteExecution|null;opencode_url:string;mcp_url:string|null;opencode_model:string|null;opencode_controller_model:string|null;opencode_env_file:string|null;max_rounds:number;execution_mode:string;delivery_mode:string;max_active_tasks:number;allow_parallel_writers:boolean;auto_approve_state_directory:boolean;auto_approve_permissions:string[];auto_approve_external_directories:string[]}
export interface Round {number:number;status:string;findings:unknown;checkpoint:unknown;verification:Record<string,unknown>|null}
export interface TaskSummary {task_id:string;project_id:string;title:string;status:string;updated_at:string;revision:string}
export interface RoundPage {rounds:Round[];next_before:number|null}
export interface Task extends TaskSummary,RoundPage {recoverable:boolean;revision_count:number;execution_mode:string;delivery_mode:string;delivery_state:string|null;delivery_refusal:{code:string;created_at:string}|null;workflow_id:string|null;depends_on:unknown;usage:unknown;budget:unknown;base_head:string|null;allowed_paths:string[];test_commands:string[];repositories:unknown}
export interface Snapshot {tasks:TaskSummary[];total:number;active_count:number;writer_count:number;waiting_count:number;reservations:Record<string,unknown>[];runs:Record<string,unknown>[];errors:Record<string,unknown>[];offset:number;limit:number}
export interface Review {review_id:string;before:Project|null;after:Project;credentials_changed:boolean}
export type TerminalEvent={type:'data';sequence:number;bytes:number[]}|{type:'exit';code:number}|{type:'error';message:string};
export const statuses:Record<string,string>={implementing:'В работе',revising:'Доработка',awaiting_review:'На проверке',needs_user:'Нужен ответ',waiting_dependencies:'Ждёт зависимости',accepted:'Принята',closed:'Закрыта',failed:'Ошибка',delivery_unknown:'Доставка неизвестна'};
